import { expect, test, type APIResponse } from '@playwright/test'

/**
 * THE HEADERS EVERY RESPONSE CARRIES — Phase 41, run for the first time in Phase 42.
 *
 * `lib/security/headers.ts` declares them and `proxy.ts` attaches them. Both are unit-tested. What
 * neither can prove is that they SURVIVE THE JOURNEY: a header set in middleware can be dropped by
 * a route that constructs its own response, by a redirect, by a static asset served before
 * middleware runs, or by a framework upgrade that changes when middleware executes.
 *
 * So every assertion here reads a real response over HTTP.
 *
 * IT RUNS AT ONE WIDTH. Headers do not vary by viewport, and running eight identical copies would
 * make a header regression look like eight failures. `test.skip` on the other seven keeps the
 * report honest about what was actually checked.
 */

const STATIC_HEADERS: readonly [string, string][] = [
  ['strict-transport-security', 'max-age=63072000; includeSubDomains; preload'],
  ['x-content-type-options', 'nosniff'],
  ['referrer-policy', 'strict-origin-when-cross-origin'],
  ['cross-origin-opener-policy', 'same-origin'],
  ['x-frame-options', 'DENY'],
]

/** One route of each class the proxy matches: a CMS page, a catalogue route, an API route. */
const ROUTES = ['/', '/collection', '/api/vitals']

/**
 * Routes the matcher EXCLUDES, deliberately (`proxy.ts` `config.matcher`).
 *
 * They are machine-read text with no markup, no script and no session, generated by route handlers
 * and cached hard. Running the proxy over them would add a hop to every crawl for a policy that
 * protects nothing. Asserted here so the decision is pinned: widening the matcher later should be
 * somebody's choice, and narrowing it by accident should fail.
 */
const UNMATCHED = ['/robots.txt', '/sitemap.xml']

test.describe('security headers', () => {
  test.skip(({ viewport }) => viewport?.width !== 1440, 'headers do not vary by viewport')

  test('every route carries the static set', async ({ request }) => {
    for (const route of ROUTES) {
      const response: APIResponse = await request.fetch(route, {
        method: route === '/api/vitals' ? 'POST' : 'GET',
        data: route === '/api/vitals' ? {} : undefined,
        failOnStatusCode: false,
      })
      const headers = response.headers()
      for (const [name, value] of STATIC_HEADERS) {
        expect(headers[name], `${route} is missing ${name}`).toBe(value)
      }
    }
  })

  test('every route carries a content security policy with a per-request nonce', async ({
    request,
  }) => {
    /*
     * THE NONCE MUST DIFFER BETWEEN TWO REQUESTS, and that is the assertion worth making. A policy
     * with a CONSTANT nonce is worse than no nonce: it reads as protection and an injected script
     * can simply carry the value, which is public in the header of every page.
     */
    const first = await request.get('/')
    const second = await request.get('/')

    const header =
      first.headers()['content-security-policy'] ??
      first.headers()['content-security-policy-report-only']
    expect(header, 'no content security policy at all').toBeTruthy()

    const nonceOf = (value: string | undefined): string | null =>
      /'nonce-([A-Za-z0-9+/=_-]+)'/.exec(value ?? '')?.[1] ?? null

    const a = nonceOf(header)
    const b = nonceOf(
      second.headers()['content-security-policy'] ??
        second.headers()['content-security-policy-report-only'],
    )
    expect(a, 'the policy carries no nonce').not.toBeNull()
    expect(b).not.toBeNull()
    expect(a, 'the same nonce was served twice — an injected script could just use it').not.toBe(b)
  })

  test('the policy names a report endpoint', async ({ request }) => {
    // A report-only policy that reports nowhere is a policy nobody will ever learn anything from.
    const response = await request.get('/')
    const header =
      response.headers()['content-security-policy'] ??
      response.headers()['content-security-policy-report-only']
    expect(header).toContain('/api/csp-report')
  })

  test('the policy forbids an object and a base tag', async ({ request }) => {
    const response = await request.get('/')
    const header =
      response.headers()['content-security-policy'] ??
      response.headers()['content-security-policy-report-only']
    expect(header).toContain("object-src 'none'")
    expect(header).toContain("base-uri 'self'")
    // `frame-ancestors` is the one X-Frame-Options cannot express per-origin.
    expect(header).toContain("frame-ancestors 'none'")
  })

  test('a redirect carries the headers too', async ({ request }) => {
    /*
     * A REDIRECT IS A RESPONSE A BROWSER ACTS ON. A 308 without `X-Content-Type-Options` or a
     * policy is a real gap, and it is the one most likely to be missed: middleware that returns
     * early to redirect is exactly where a header set gets skipped.
     */
    const response = await request.get('/studio/products', { maxRedirects: 0 })
    expect([301, 302, 303, 307, 308]).toContain(response.status())
    for (const [name, value] of STATIC_HEADERS) {
      expect(response.headers()[name], `the redirect is missing ${name}`).toBe(value)
    }
  })

  test('names no server and no framework version', async ({ request }) => {
    // `x-powered-by` tells an attacker which advisories to read. Nothing here should answer that.
    const headers = (await request.get('/')).headers()
    expect(headers['x-powered-by']).toBeUndefined()
  })

  test('does not run the proxy over the crawler files', async ({ request }) => {
    for (const route of UNMATCHED) {
      const response = await request.get(route, { failOnStatusCode: false })
      // They must still answer — an excluded route is not a missing one.
      expect(response.status(), `${route} does not answer`).toBeLessThan(400)
      expect(
        response.headers()['content-security-policy-report-only'] ??
          response.headers()['content-security-policy'],
        `${route} now goes through the proxy — intended, or an accidental matcher change?`,
      ).toBeUndefined()
    }
  })

  test('a Studio route is never cached by a shared cache', async ({ request }) => {
    /*
     * A STUDIO RESPONSE IS PER-SESSION. `public` or a missing `cache-control` on a route behind
     * authentication is how one person's draft reaches another person's browser through a CDN.
     */
    const response = await request.get('/studio', { maxRedirects: 0 })
    const cacheControl = response.headers()['cache-control'] ?? ''
    expect(cacheControl).not.toContain('public')
  })
})
