/**
 * THE TEXT ALTERNATIVE FOR EACH OF THE 250 MIGRATED ASSETS — Phase 43.
 *
 * GENERATED BY `npx tsx scripts/media/build-alt-text.ts`, AND EDITABLE BY HAND. The generator
 * derives a first sentence from each prompt by keeping the scene and dropping the instructions;
 * a person who has looked at the picture improves it, and the improvement is a reviewable diff
 * in this file rather than an invisible change in a database.
 *
 * A PROMPT DESCRIBES WHAT WAS ASKED FOR. Only somebody looking at the image can say what
 * arrived, so every value here stays `OWNER_VERIFICATION_REQUIRED` until an editor approves it
 * in the Studio's alt-text queue, which orders bound assets first.
 *
 * `npm run media:rewrite-alt-text` carries these values into `media_assets.alt_text`.
 * `npm run media:check-alt-text` holds every value here to the SEED §43 rules.
 */

export const ALT_TEXT: Readonly<Record<string, string>> = {
  'PROCESS-STUDIO-001':
    'A studio tool wall: heat guns, notched spreaders, a digital scale, clamps and mixing sticks hung and racked in deliberate order above a working bench.',
  'WORKSHOP-SESSION-001':
    'An evening private workshop: four seats along one end of a long table under two warm pendant lamps, hands and aprons only.',
  'PROCESS-CURE-001':
    'A dedicated cure room seen from the doorway: a steel rack of levelled shelves holding filled moulds at different stages, a light dust cover half drawn back, a thermometer on the wall.',
  'DECOR-001':
    'A resin coaster, a domed paperweight and a slim pen rest arranged in a loose diagonal across a dark bench, each piece showing sapphire depth and a thread of champagne.',
  'PROCESS-MOULD-001':
    'One pair of gloved hands tipping a mixing cup into a small mould in the centre of frame while three other pairs of hands rest on the table around it watching, everyone cropped at the forearm, warm overhead light.',
  'PRESERVATION-VARMALA-001':
    'A fresh marigold-and-rose wedding varmala coiled on a seasoned dark teak workbench, still bright, blotting paper and a pair of trimming scissors laid beside it, the garland whole and untouched.',
  'PRESERVATION-VARMALA-002':
    'One garland photographed twice on the same dark teak ground: on the left the fresh marigold and rose varmala coiled loose, on the right the same flowers preserved and sealed inside a clear resin block.',
  'GIFTS-001':
    'An open square gift box lined with dark charcoal cloth holding three small resin keepsakes — a coaster, a domed paperweight and a pendant — the lid resting behind it, a length of champagne ribbon loose alongside.',
  'PRESERVATION-KEEPSAKE-001':
    'A sealed rectangular preservation block curing on a levelled bench under one warm work lamp, a full ring of marigold and rose petals suspended in its depth, the resin surface still glass-wet.',
  'GIFTS-002':
    'Eight identical resin-and-teak desk pieces laid out in one even row across a long dark bench for a bulk corporate order, each, the repetition itself the subject, receding gently out of focus at the far end.',
  'WALL-ART-001':
    'A rectangular resin-and-teak plaque blank standing on edge against a matte obsidian wall, its poured sapphire band running the length of the timber, the surface polished and entirely blank ready for engraving.',
  'MATERIAL-MACRO-001':
    'Extreme macro of a single preserved marigold floret suspended in cured clear resin, every petal edge and vein resolved, faint champagne warmth in the flower against deep sapphire depth behind it.',
  'PROCESS-MOULD-002':
    'A wide shallow mould part-filled with clear resin on a dark bench, preserved marigold petals arranged into the surface of a second layer with a fine tool, the left third of the frame falling away into quiet unlit shadow.',
  'GIFTS-003':
    'Gloved hands drawing a muted champagne ribbon into a knot around a small wrapped keepsake box on a dark bench, tissue and a folded card beside it, hands cropped at the wrist.',
  'INTERIOR-LIFESTYLE-001':
    'A stack of wooden flower presses clamped under cast-iron weights on a studio shelf, small dated paper labels tucked between the layers, dried petals just visible at the edges of each board.',
  'DECOR-002':
    'A round resin pooja thali with a poured sapphire and champagne swirl through its base, two small unlit clay diyas and a few loose marigold petals arranged on it, resting on dark teak, warm light.',
  'PRESERVATION-VARMALA-003':
    'Marigold and rose petals separated from a garland and graded by size in neat rows across cream blotting paper, fine tweezers resting at the frame edge, a few petals still deep and saturated while others have dried paler.',
  'PROCESS-FINISH-001':
    'A cured resin tabletop mid wet-sand, a sanding block resting at an angle on its surface.',
  'PROCESS-POUR-001':
    'Deep sapphire resin pouring in one unbroken ribbon into a shallow round mould against a matte obsidian background, keeping the same subject.',
  'PROCESS-FINISH-002':
    'A foam polishing pad mid-pass across a large resin surface, a mirror-bright arc of finished gloss trailing behind it against the still-matte resin ahead of it, the reflected light stretched along the polished band.',
  'WALL-ART-002':
    'A calm, unstyled bedroom — a plain bed, muted linen, neutral walls — with one large abstract resin wall panel as the single point of colour in an otherwise neutral, unstyled room.',
  'WALL-ART-003':
    'A spare study — a plain desk, one chair, a bare bookshelf, neutral walls — with one large abstract resin wall panel as the single point of colour in an otherwise neutral, unstyled room.',
  'MATERIAL-MACRO-002':
    'A close-up of the texture of poured resin, keeping the same subject, palette and light as the horizontal master so the crop reads as the same photograph, not a new scene.',
  'PROCESS-POUR-002':
    'A single frame of sapphire resin mid-pour into a shallow mould against a matte black background, keeping the same subject, palette and light as the horizontal master so the crop reads as the same photograph.',
  'PROCESS-CURE-002':
    'A dark studio interior with a work bench of curing large-format moulds under one warm lamp, keeping the same subject, palette and light as the horizontal master so the crop reads as the same photograph, not a new scene.',
  'MATERIAL-MACRO-003':
    'A close-up of the texture of poured resin, keeping the same subject, palette and light as the horizontal master so the crop reads as the same photograph, not a new scene.',
  'DECOR-003':
    'A long shared workshop table set with pour cups and moulds under warm pendant light, keeping the same subject, palette and light as the horizontal master so the crop reads as the same photograph, not a new scene.',
  'MATERIAL-MACRO-004':
    'A wide macro texture band of poured resin, keeping the same subject, palette and light as the horizontal master so the crop reads as the same photograph, not a new scene.',
  'DECOR-004':
    'A long shared workshop table set with pour cups and moulds under warm pendant light, keeping the same subject, palette and light as the horizontal master so the crop reads as the same photograph, not a new scene.',
  'MATERIAL-MACRO-005':
    'A wide macro texture band of poured resin, keeping the same subject, palette and light as the horizontal master so the crop reads as the same photograph, not a new scene.',
  'PROCESS-CURE-003':
    'A dark studio interior with a work bench of curing large-format moulds under one warm lamp, keeping the same subject, palette and light as the horizontal master so the crop reads as the same photograph, not a new scene.',
  'PROCESS-POUR-003':
    'A single frame of sapphire resin mid-pour into a shallow mould against a matte black background, keeping the same subject, palette and light as the horizontal master so the crop reads as the same photograph.',
  'PROCESS-FINISH-003':
    'A cured resin tabletop mid wet-sand, a sanding block resting at an angle on its surface.',
  'EDITORIAL-001':
    'A finished resin tabletop tilted up at an angle so every ripple in the gloss would show, the surface reading perfectly flat and even, the edge of a hand just entering the bottom of frame to hold the angle, no face.',
  'PROCESS-POUR-004':
    'Deep sapphire resin pouring in one unbroken ribbon into a shallow round mould against a matte obsidian background, keeping the same subject.',
  'EDITORIAL-002':
    'A finished resin tabletop tilted up at an angle so every ripple in the gloss would show, the surface reading perfectly flat and even, the edge of a hand just entering the bottom of frame to hold the angle, no face.',
  'PROCESS-FINISH-004':
    'A foam polishing pad mid-pass across a large resin surface, a mirror-bright arc of finished gloss trailing behind it against the still-matte resin ahead of it, the reflected light stretched along the polished band.',
  'PROCESS-TIMBER-001':
    "A rough-sawn timber slab clamped to a workshop bench, a hand plane mid-stroke along its edge, pale shavings curling off and scattered beneath, the slab's live edge bare of resin.",
  'PROCESS-PIGMENT-001':
    'A glass mixing jug of clear epoxy resin on a scale, a stir stick lifting a ribbon of deep sapphire pigment paste through the clear liquid mid-blend, the swirl only half-dissolved.',
  'WALL-ART-004':
    'A spare study — a plain desk, one chair, a bare bookshelf, neutral walls — with one large abstract resin wall panel as the single point of colour in an otherwise neutral, unstyled room.',
  'WALL-ART-005':
    'A plain dining room — a bare table, simple chairs, neutral walls — with one large abstract resin wall panel as the single point of colour in an otherwise neutral, unstyled room.',
  'PROCESS-PIGMENT-002':
    'A glass mixing jug of clear epoxy resin on a scale, a stir stick lifting a ribbon of deep sapphire pigment paste through the clear liquid mid-blend, the swirl only half-dissolved.',
  'PROCESS-TIMBER-002':
    "A rough-sawn timber slab clamped to a workshop bench, a hand plane mid-stroke along its edge, pale shavings curling off and scattered beneath, the slab's live edge bare of resin.",
  'WALL-ART-006':
    'A plain dining room — a bare table, simple chairs, neutral walls — with one large abstract resin wall panel as the single point of colour in an otherwise neutral, unstyled room.',
  'WALL-ART-007':
    'A calm, unstyled bedroom — a plain bed, muted linen, neutral walls — with one large abstract resin wall panel as the single point of colour in an otherwise neutral, unstyled room.',
  'WALL-ART-008':
    'A very wide, low resin panel, a single soft horizontal gradient running from deep-ocean blue at the top to a warm champagne line low in the frame, entirely abstract.',
  'WALL-ART-009':
    'A quiet, unstyled living room — a low sofa, a plain rug, muted grey walls, warm wood floor — with one large abstract resin wall panel as the single point of colour in an otherwise neutral, unstyled room.',
  'WALL-ART-010':
    'A quiet, unstyled living room — a low sofa, a plain rug, muted grey walls, warm wood floor — with one large abstract resin wall panel as the single point of colour in an otherwise neutral, unstyled room.',
  'WALL-ART-011':
    'A large abstract resin wall panel leaning unmounted against a bare obsidian studio wall, deep sapphire pours swirling over a near-black ground with a single champagne vein through it, no frame, no hanging hardware.',
  'WALL-ART-012':
    'A large abstract resin wall panel leaning unmounted against a bare obsidian studio wall, deep sapphire pours swirling over a near-black ground with a single champagne vein through it, no frame, no hanging hardware.',
  'MATERIAL-MACRO-006':
    'A tight square macro of a large abstract resin pour, obsidian and deep sapphire swirling together around one fine champagne-gold thread, shot close enough that no edge of the panel is visible, pure abstract surface.',
  'WALL-ART-013':
    'A very wide, low resin panel, a single soft horizontal gradient running from deep-ocean blue at the top to a warm champagne line low in the frame, entirely abstract.',
  'MATERIAL-MACRO-007':
    'A tight square macro of a large abstract resin pour, obsidian and deep sapphire swirling together around one fine champagne-gold thread, shot close enough that no edge of the panel is visible, pure abstract surface.',
  'WALL-ART-014':
    'A large resin panel built from many thin layered pours, the palest sapphire at the top deepening through mid-tone blue to near-obsidian at the base.',
  'WALL-ART-015':
    'A large resin panel built from many thin layered pours, the palest sapphire at the top deepening through mid-tone blue to near-obsidian at the base.',
  'PROCESS-MOULD-003':
    'A round coffee-table blank in raw formwork, sapphire-tinted resin filling a live-edge seam down its centre, spring clamps holding the mould rim, seen close from table height, no finished legs attached, no room around it.',
  'LARGEFORMAT-SEATING-001':
    'A single curved chair-seat blank, laminated timber and a thin sapphire resin seam, still resting inside its curved plywood mould on a bench, weights holding the laminate down, no legs or frame attached.',
  'LARGEFORMAT-CONSOLE-001':
    'A long narrow console-table plank, alternating bands of teak and sapphire resin, clamped edge to edge along a workshop bench under a single hanging lamp, a hand router and a bag of sawdust resting to one side.',
  'PROCESS-MOULD-004':
    'A round coffee-table blank in raw formwork, sapphire-tinted resin filling a live-edge seam down its centre, spring clamps holding the mould rim, seen close from table height, no finished legs attached, no room around it.',
  'LARGEFORMAT-SIDE-001':
    'A small round side-table blank on a bench, one layer of resin already cured to a pale sapphire disc, a dam of masking tape built up around its rim ready for a second pour, a jug of mixed resin waiting beside it.',
  'LARGEFORMAT-SEATING-002':
    'A long bench-seat plank, a single sapphire resin river running down the centre of the timber, resting on two sawhorse trestles, its edge still rough and unsanded, wood shavings on the floor beneath.',
  'LARGEFORMAT-CONSOLE-002':
    'A long narrow console-table plank, alternating bands of teak and sapphire resin, clamped edge to edge along a workshop bench under a single hanging lamp, a hand router and a bag of sawdust resting to one side.',
  'LARGEFORMAT-SIDE-002':
    'A small round side-table blank on a bench, one layer of resin already cured to a pale sapphire disc, a dam of masking tape built up around its rim ready for a second pour, a jug of mixed resin waiting beside it.',
  'LARGEFORMAT-SEATING-003':
    'A long bench-seat plank, a single sapphire resin river running down the centre of the timber, resting on two sawhorse trestles, its edge still rough and unsanded, wood shavings on the floor beneath.',
  'LARGEFORMAT-SEATING-004':
    'A single curved chair-seat blank, laminated timber and a thin sapphire resin seam, still resting inside its curved plywood mould on a bench, weights holding the laminate down, no legs or frame attached.',
  'PROCESS-STUDIO-002':
    'A long rectangular slab destined to become a dining table, resin poured into a live-edge timber void and still curing inside its clamped formwork on a low workshop bench, sawdust and a spirit level beside it.',
  'PROCESS-STUDIO-003':
    'A long rectangular slab destined to become a dining table, resin poured into a live-edge timber void and still curing inside its clamped formwork on a low workshop bench, sawdust and a spirit level beside it.',
  'MATERIAL-MACRO-008':
    'Macro top-down view of liquid deep sapphire blue epoxy resin flowing across raw dark teakwood, swirling with genuine gold leaf veins, crystalline water-like refraction.',
  'PROCESS-TIMBER-003':
    "Lens, framing, background wall, trestles and the slab's silhouette and position IDENTICAL — this must read as the same object photographed a second time in the same spot.",
  'PROCESS-TIMBER-004':
    'A single large timber slab supported on two blackened steel trestles in a dark artisan atelier, board-formed concrete wall behind, one soft directional window light from the left.',
  'EDITORIAL-003':
    'Ultra-wide editorial photograph composed as a social share card: a single flagship live-edge black walnut dining table with a translucent deep ocean blue epoxy resin river, three-quarter view.',
  'PROCESS-TIMBER-005':
    'A single large timber slab supported on two blackened steel trestles in a dark artisan atelier, board-formed concrete wall behind, one soft directional window light from the left.',
  'EDITORIAL-004':
    'Editorial photograph: tall studio window light falling across several resin pieces resting on trestles while they cure, plastic sheeting folded neatly aside, dark timber and mineral surfaces, quiet morning stillness.',
  'PRESERVATION-VARMALA-004':
    'Atmospheric macro, portrait: marigold and rose petals suspended mid-drift in perfectly clear resin, soft warm side-light through the glassy block, edges falling to soft darkness.',
  'PROCESS-PIGMENT-003':
    'Portrait abstract for social: deep ocean blue resin folds with fine white pigment lace, glassy depth, calm dark lower third suitable for quiet text overlay. Quiet luxury, never plastic. No objects, no neon.',
  'LARGEFORMAT-DINING-001':
    'Soft morning side-light, the upper third of the frame calm and near-empty as headline safe area. Quiet luxury, materials never plastic, realistic proportions., no neon, no heavy gold.',
  'EDITORIAL-005':
    'Editorial photograph: a bespoke consultation table from above at a shallow angle.',
  'PRESERVATION-KEEPSAKE-002':
    'Square atmospheric still life: a small clear resin keepsake block holding preserved petals, resting on dark mineral stone beside one stem, single soft directional light, deep quiet shadow.',
  'MATERIAL-MACRO-009':
    'Ultra-wide abstract macro: deep ocean blue resin in slow frozen flow, white mineral veils suspended mid-bloom, faint champagne warmth at one edge, glass-deep gloss.',
  'PROCESS-PIGMENT-004':
    'Abstract macro photograph: a thin champagne-warm veil of pigment folded into obsidian-dark resin, one soft directional light finding the fold, everything else falling to near-black.',
  'INTERIOR-LIFESTYLE-002':
    'Editorial interior photograph, Japandi style: a resin and oak dining table with a clear smoky epoxy seam, low warm light, paper lantern, tatami-toned textures, deep calm shadows and large negative space. Quiet luxury.',
  'EDITORIAL-006':
    'Still life, square editorial photograph: pigment jars in deep ocean blues, a brass mixing tool, resin cups and a strip of walnut arranged sparsely on a dark mineral bench, one soft directional light, precise shadows.',
  'LARGEFORMAT-CONSOLE-003':
    'Modern tropical entryway, editorial photograph: a long resin console table with teak grain flowing into clear epoxy against a lime-plaster wall, monstera shadow play from side light, breeze-lit calm.',
  'WALL-ART-016':
    'Gallery wall, editorial portrait: a very large abstract resin wall artwork in deep ocean blues with fine champagne mineral veining, a low oak bench beneath, huge negative space. Quiet luxury.',
  'INTERIOR-LIFESTYLE-003':
    'Softened brutalist interior, editorial portrait: a sculptural resin chair with a translucent smoky seat and dark timber frame against board-formed concrete, one warm directional light, strong architectural shadow.',
  'INTERIOR-LIFESTYLE-004':
    'Modern Mediterranean room, editorial photograph: a low resin and olive-wood bench beneath an arched window, whitewashed textured walls, warm late light raking across the polished resin seat.',
  'LARGEFORMAT-COFFEE-001':
    'Warm minimalist living room, editorial photograph: a round resin coffee table with deep ocean blue surface and walnut base on a wool rug, linen sofa in mineral tones, one shaft of afternoon light.',
  'LARGEFORMAT-DINING-002':
    'Ultra-wide architectural editorial photograph: a large live-edge resin dining table with a deep ocean blue epoxy river through natural walnut, centered in an organic-modern interior with rammed-earth walls.',
  'LARGEFORMAT-MONUMENTAL-001':
    "Ultra-wide architectural lobby, editorial photograph: a monumental freestanding resin and timber sculptural piece as the space's single statement, polished stone floor reflecting it faintly, tall diffuse daylight.",
  'PROCESS-FINISH-005':
    "Close editorial photograph: a craftsman's hands only, no face, sanding the live edge of a walnut and resin tabletop, fine dust on skin, soft warm directional light from the side.",
  'PROCESS-STUDIO-004':
    'Dark premium artisan atelier, wide editorial photograph: a long timber workbench holding a half-finished resin tabletop, clamps and hand tools arranged quietly, dark timber walls and mineral surfaces.',
  'GALLERY-SCENE-001':
    'Gallery-like interior, editorial portrait orientation: a small sculptural resin side table with layered blue and clear casting beside a concrete plinth, single artwork on a distant wall, vast negative space. Quiet luxury.',
  'PROCESS-MOULD-005':
    'Hands in black nitrile gloves arranging marigold and rose petals inside an empty silicone mould on a dark work surface, intimate, cropped at the wrists in frame.',
  'THREE-D-RESIN-001':
    'One frame from a six-part collection series, all shot in a single session on the same seasoned dark teak tabletop, same single soft directional key from upper left with a warm champagne rim, same lens.',
  'MATERIAL-MACRO-010':
    'One of four material macros, same magnification, same lens, same framing, so the four tile together as one set. Frame: extreme macro of a loose heap of mineral pigment powder in deep ocean blue.',
  'MATERIAL-MACRO-011':
    'Extreme macro of a cured resin surface, one champagne gold vein running through deep sapphire.',
  'WORKSHOP-SESSION-002':
    'A small group of four people seated along one side of a craft studio table, warm ambient light, their hands working resin and moulds, framed from chest height downward so every face is out of frame above the top edge.',
  'MATERIAL-MACRO-012':
    'Macro top-down view of liquid deep sapphire blue epoxy resin flowing across raw dark teakwood, swirling with genuine gold leaf veins, crystalline water-like refraction.',
  'EDITORIAL-007':
    'One frame from a six-part collection series, all shot in a single session on the same seasoned dark teak tabletop, same single soft directional key from upper left with a warm champagne rim, same lens.',
  'MATERIAL-MACRO-013':
    'One frame from a four-part material story shot in a single session, same lens, same single soft key from upper left, same cool shadow falloff.',
  'PROCESS-MOULD-006':
    'A single empty, freshly demoulded silicone mould lying on a pale warm stone ground, soft light, a lot of quiet empty space around it.',
  'PROCESS-STUDIO-005':
    'The interior of a dark artisan resin studio at night, a single warm work lamp over a bench of curing moulds, deep shadow beyond it, tools and pigment jars on a shelf out of focus behind.',
  'PROCESS-STUDIO-006':
    'Artisan hands in black nitrile gloves using a precision heat gun to draw fine wave patterns across deep blue liquid resin in a shallow tray, studio workshop, cropped at the forearms so no face is in frame.',
  'EDITORIAL-008':
    'Abstract dark navy and midnight blue fluid resin slowly swirling with soft golden luminescence deep inside it, entirely out of focus, no recognisable object, calm ambient field.',
  'PROCESS-STUDIO-007':
    'The interior of a dark artisan resin studio at night, a single warm work lamp over a bench of curing moulds, deep shadow beyond it, tools and pigment jars on a shelf out of focus behind.',
  'PROCESS-STUDIO-008':
    'Artisan hands in black nitrile gloves using a precision heat gun to draw fine wave patterns across deep blue liquid resin in a shallow tray, studio workshop, cropped at the forearms so no face is in frame.',
  'EDITORIAL-009':
    'Abstract dark navy and midnight blue fluid resin slowly swirling with soft golden luminescence deep inside it, entirely out of focus, no recognisable object, calm ambient field.',
  'PROCESS-MOULD-007':
    'A single empty, freshly demoulded silicone mould lying on a pale warm stone ground, soft light, a lot of quiet empty space around it.',
  'WORKSHOP-SESSION-003':
    'A long dark studio table set for eight places with mixing cups, folded gloves, pigment jars and empty moulds laid out in a row, soft morning light from a side window in frame.',
  'MATERIAL-MACRO-014':
    'Macro top-down view of liquid deep sapphire blue epoxy resin flowing across raw dark teakwood, swirling with genuine gold leaf veins, crystalline water-like refraction.',
  'THREE-D-RESIN-002':
    'Macro of an FDM 3D print head laying translucent blue filament layer by layer onto a build plate, warm work lamp raking across the fresh layer lines, shallow focus.',
  'WORKSHOP-SESSION-004':
    'A small group of four people seated along one side of a craft studio table, warm ambient light, their hands working resin and moulds, framed from chest height downward so every face is out of frame above the top edge.',
  'PROCESS-MOULD-008':
    'Hands in black nitrile gloves arranging marigold and rose petals inside an empty silicone mould on a dark work surface, intimate, cropped at the wrists in frame.',
  'MATERIAL-MACRO-015':
    'Extreme macro of a cured resin surface, one champagne gold vein running through deep sapphire.',
  'WORKSHOP-SESSION-005':
    'A long dark studio table set for eight places with mixing cups, folded gloves, pigment jars and empty moulds laid out in a row, soft morning light from a side window in frame.',
  'THREE-D-RESIN-003':
    'Macro of an FDM 3D print head laying translucent blue filament layer by layer onto a build plate, warm work lamp raking across the fresh layer lines, shallow focus.',
  'MATERIAL-MACRO-016':
    'One of four material macros, same magnification, same lens, same framing, so the four tile together as one set. Frame: extreme macro of a loose heap of mineral pigment powder in deep ocean blue.',
  'MATERIAL-MACRO-017':
    'One of four material macros, same magnification, same lens, same framing, so the four tile together as one set. Frame: extreme macro of a single pressed and dried flower lying flat on the ground.',
  'MATERIAL-MACRO-018':
    'One of four material macros, same magnification, same lens, same framing, so the four tile together as one set. Frame: extreme macro of the edge of a slab of cured clear epoxy.',
  'MATERIAL-MACRO-019':
    'One of four material macros, same magnification, same lens, same framing, so the four tile together as one set. Frame: extreme macro of the edge of a slab of cured clear epoxy.',
  'MATERIAL-MACRO-020':
    'One of four material macros, same magnification, same lens, same framing, so the four tile together as one set. Frame: extreme macro of seasoned teak grain meeting a poured edge of deep blue resin, the join line sharp.',
  'MATERIAL-MACRO-021':
    'One of four material macros, same magnification, same lens, same framing, so the four tile together as one set. Frame: extreme macro of a single pressed and dried flower lying flat on the ground.',
  'MATERIAL-MACRO-022':
    'One of four material macros, same magnification, same lens, same framing, so the four tile together as one set. Frame: extreme macro of seasoned teak grain meeting a poured edge of deep blue resin, the join line sharp.',
  'PROCESS-CURE-004':
    'One frame from a four-part material story shot in a single session, same lens, same single soft key from upper left, same cool shadow falloff.',
  'PROCESS-POUR-005':
    'One frame from a four-part material story shot in a single session, same lens, same single soft key from upper left, same cool shadow falloff.',
  'PROCESS-POUR-006':
    'One frame from a four-part material story shot in a single session, same lens, same single soft key from upper left, same cool shadow falloff.',
  'PROCESS-CURE-005':
    'One frame from a four-part material story shot in a single session, same lens, same single soft key from upper left, same cool shadow falloff.',
  'MATERIAL-MACRO-023':
    'One frame from a four-part material story shot in a single session, same lens, same single soft key from upper left, same cool shadow falloff.',
  'PRESERVATION-VARMALA-005':
    'One frame from a six-part collection series, all shot in a single session on the same seasoned dark teak tabletop, same single soft directional key from upper left with a warm champagne rim, same lens.',
  'DECOR-005':
    'One frame from a six-part collection series, all shot in a single session on the same seasoned dark teak tabletop, same single soft directional key from upper left with a warm champagne rim, same lens.',
  'PROCESS-MOULD-009':
    'One frame from a six-part collection series, all shot in a single session on the same seasoned dark teak tabletop, same single soft directional key from upper left with a warm champagne rim, same lens.',
  'DECOR-006':
    'One frame from a six-part collection series, all shot in a single session on the same seasoned dark teak tabletop, same single soft directional key from upper left with a warm champagne rim, same lens.',
  'THREE-D-RESIN-004':
    'One frame from a six-part collection series, all shot in a single session on the same seasoned dark teak tabletop, same single soft directional key from upper left with a warm champagne rim, same lens.',
  'PROCESS-MOULD-010':
    'One frame from a six-part collection series, all shot in a single session on the same seasoned dark teak tabletop, same single soft directional key from upper left with a warm champagne rim, same lens.',
  'EDITORIAL-010':
    'One frame from a six-part collection series, all shot in a single session on the same seasoned dark teak tabletop, same single soft directional key from upper left with a warm champagne rim, same lens.',
  'DECOR-007':
    'One frame from a six-part collection series, all shot in a single session on the same seasoned dark teak tabletop, same single soft directional key from upper left with a warm champagne rim, same lens.',
  'PRESERVATION-VARMALA-006':
    'One frame from a six-part collection series, all shot in a single session on the same seasoned dark teak tabletop, same single soft directional key from upper left with a warm champagne rim, same lens.',
  'DECOR-008':
    'One frame from a six-part collection series, all shot in a single session on the same seasoned dark teak tabletop, same single soft directional key from upper left with a warm champagne rim, same lens.',
  'PRESERVATION-VARMALA-007':
    'Elegant hands gently lowering a red and marigold flower garland into a rectangular mold of clear liquid resin, warm candle-like backlight through translucent petals, tiny gold flakes drifting in the resin.',
  'PRESERVATION-VARMALA-008':
    'Emotional luxury still life, clear resin keepsake block preserving a red and marigold flower garland, standing upright on a dark reflective surface, warm backlight glowing through translucent petals.',
  'PROCESS-POUR-007':
    'Wide hero still, macro liquid epoxy resin mid-pour cascading like a slow ocean wave, deep midnight-blue background flowing into royal blue depths, suspended gold-leaf flakes catching backlight.',
  'PROCESS-STUDIO-009':
    'Artisan craft process still, gloved hands tilting a wooden mold with freshly poured translucent deep-blue resin, gold flakes swirling in the liquid, workshop softly lit, deep midnight-blue tones.',
  'DECOR-009':
    'Macro product photography, oval gold-leaf geode resin serving tray with polished agate-style rings, deep midnight-blue background, sapphire and royal blue translucent resin bands, suspended gold flakes.',
  'PRESERVATION-VARMALA-009':
    'Macro product photography, clear resin keepsake block preserving red and marigold wedding garland flowers, deep midnight-blue background, embedded rose petals and marigold blossoms suspended in crystal-clear resin.',
  'MATERIAL-MACRO-024':
    'Extreme macro cinematography still, liquid epoxy resin mid-pour swirling deep sapphire and royal blue pigment, suspended gold-leaf flakes catching light, deep midnight-blue background, backlit translucency.',
  'DECOR-010':
    'Macro product photography, teardrop resin pendant necklace with deep blue translucent resin and suspended gold-leaf flakes, tiny pressed white flowers inside, deep midnight-blue background, backlit translucency.',
  'MATERIAL-MACRO-025':
    'Macro product photography, set of round ocean-wave resin coasters, deep midnight-blue background, translucent teal and white resin waves with fine gold-leaf veins, backlit translucency, caustic light refraction.',
  'PROCESS-STUDIO-010':
    'Bright porcelain-toned artisan studio table by a large window, soft ivory daylight, handmade resin coasters with ocean-wave edges and small brass tools arranged neatly on pale linen, airy negative space.',
  'THREE-D-RESIN-005':
    'Modern 3D printer mid-print of a translucent geometric sculptural vase, glowing blue LED light from the print chamber, dark studio environment with deep sapphire tones, fine printed layer lines visible.',
  'MATERIAL-MACRO-026':
    'Abstract extreme macro of cured resin surface: deep sapphire and midnight blue marbling with delicate antique-gold veins, glossy glass-like finish, soft specular highlights, elegant dark background texture.',
  'GALLERY-SCENE-002':
    'Wide shot of a dark midnight-blue gallery room with handcrafted resin objects displayed on stone plinths of varying heights — trays, clocks, sculptural bowls — each under its own narrow spotlight, museum archive mood.',
  'PROCESS-STUDIO-011':
    'Macro of a small artisan torch flame passing over a freshly poured resin surface, tiny bubbles rising and popping, wet glossy deep-blue surface with gold shimmer, dark atelier background.',
  'WALL-ART-017':
    'Dark contemporary gallery wall with three framed ocean-resin art panels in deep blues with fine gold leaf detail, museum picture lights, stone floor reflection, luxury art-gallery editorial photograph.',
  'PROCESS-PIGMENT-005':
    'Still life of resin art supplies: glass jars of shimmering mica pigment powders in blues and golds, amber bottles, a brass stirring stick, arranged on dark slate against a deep midnight-blue background.',
  'PROCESS-MOULD-011':
    "Close-up of an artisan's hands placing dried red rose and marigold wedding-garland petals into a circular silicone mold, dark workshop with a single warm spotlight, deep blue shadows, craft documentary luxury photography.",
  'DECOR-011':
    'A handcrafted deep-blue resin serving tray with gold flake edges resting on a dark marble console beside an unlit candle and a small stack of linen napkins, moody evening interior.',
  'MATERIAL-MACRO-027':
    'Extreme macro of liquid epoxy resin mid-pour, deep sapphire blue translucent liquid surface with thin veins of antique gold pigment swirling through it, glossy reflections and refraction, dark midnight-blue environment.',
  'MATERIAL-MACRO-028':
    'Extreme macro photograph of a polished resin art surface: deep translucent layers of sapphire and midnight blue with thin shimmering veins of gold leaf running through, glossy wet-look reflections.',
  'PROCESS-PIGMENT-006':
    'Vertical still life on a dark stone table: small glass jars of sapphire blue resin pigment, a brush, scattered flakes of gold leaf, one warm spotlight from the side, deep black background, luxurious minimal composition.',
  'GALLERY-SCENE-003':
    'Wide shot of a dark gallery wall at night with three framed abstract resin artworks in deep sapphire blue and gold, each lit by its own warm picture light, dark charcoal wall, moody museum atmosphere.',
  'PROCESS-PIGMENT-007':
    'Small evening resin-art workshop scene: a long dark wooden table set with individual work mats, molds, pigment cups and gloves, warm pendant lights above, cozy dark studio with blue accents.',
  'PROCESS-STUDIO-012':
    'Artisan resin studio at night: wooden workbench with silicone molds, jars of blue pigment, gold leaf sheets, a warm desk lamp glowing against cool blue window light, still life, deep shadows.',
  'PROCESS-FINISH-006':
    'Close-up of hands in dark cotton sleeves polishing a small round resin artwork with a soft cloth, glossy blue-gold surface catching warm lamp light, dark workshop background, craft photography.',
  'MATERIAL-MACRO-029':
    'A luxurious oval vanity mirror framed in ocean-blue resin with gold leaf inclusions, standing on a dark dresser with soft reflected glow. luxury product photography, handcrafted resin art.',
  'DECOR-012':
    'An elegant resin tablescape set — round serving tray, matching coasters and napkin rings in deep ocean blue resin with gold flake edges, styled on a dark linen table. luxury product photography, handcrafted resin art.',
  'MATERIAL-MACRO-030':
    'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PROCESS-FINISH-007':
    'A flat-lay of resin studio tools — torch, mixing cups, pigments, gloves, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'EDITORIAL-011': 'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PROCESS-CURE-006':
    'A planner calendar beside wrapped resin gifts and a curing piece, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PROCESS-POUR-008':
    'A step-by-step studio scene: flower drying racks, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PROCESS-FINISH-008':
    'A half-polished resin coaster showing before-and-after gloss contrast, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PRESERVATION-VARMALA-010':
    'A phone photographing a varmala under good window light on a plain background, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'LARGEFORMAT-DINING-003':
    'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PROCESS-CURE-007':
    'A curing resin piece under a dust cover with an hourglass beside it, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PRESERVATION-VARMALA-011':
    'A pristine preserved varmala frame under bright honest light, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PRESERVATION-VARMALA-012':
    'Three varmala preservation frames of increasing size leaning on a wall, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'DECOR-013':
    'A styled console vignette — resin tray, vase, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'WALL-ART-018':
    'A backlit lithophane panel glowing warmly revealing a portrait relief, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'INTERIOR-LIFESTYLE-005':
    'A resin wall clock near a rain-streaked window, monsoon mood, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'WALL-ART-019': 'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PROCESS-STUDIO-013':
    'A single artisan workbench with one piece in progress, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'GIFTS-004': 'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'GIFTS-005': 'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'LARGEFORMAT-CONSOLE-004':
    'A large ocean-wave resin wall panel above a console table, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PROCESS-PIGMENT-008':
    'Four material swatch squares — resin, glass, acrylic, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'EDITORIAL-012': 'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'THREE-D-RESIN-006':
    "A kids' room shelf with a personalized 3D-printed cloud lamp and star hooks, deep ocean-blue resin tones, with metallic gold accents, soft studio light.",
  'THREE-D-RESIN-007':
    'A detailed custom figurine on a turntable beside reference photos, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PROCESS-PIGMENT-009':
    'A composition of wedding keepsakes — invitation, haldi-stained cloth swatch, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'GALLERY-SCENE-004':
    'A single extraordinary one-of-one resin art object on a pedestal, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'THREE-D-RESIN-008':
    'A 3D printer mid-print of a decorative vase, glowing print bed, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'GIFTS-006':
    'A gift-wrapped large frame being handed over, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PROCESS-STUDIO-014':
    "A master artisan's hands leveling a large ocean-resin pour, tools and torch nearby, deep ocean-blue resin tones, with metallic gold accents, soft studio light.",
  'PROCESS-PIGMENT-010':
    'Macro of pigment dishes and ink drops swirling into ocean-blue resin, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PROCESS-PIGMENT-011':
    "A designer's moodboard with fabric swatches, deep ocean-blue resin tones, with metallic gold accents, soft studio light.",
  'EDITORIAL-013':
    'An ornate ocean-blue resin engagement ring tray with gold detailing, rings placed at center, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PRESERVATION-VARMALA-013':
    'Dried wedding flowers beside a fresh resin casting in progress, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'GIFTS-007':
    'A modern resin milestone award trophy with embedded gold flake, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'EDITORIAL-014':
    'A crystal-clear resin block held up to sunlight showing perfect clarity, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PRESERVATION-VARMALA-014':
    'A wedding varmala carefully laid flat in a breathable paper-lined box, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'DECOR-014': 'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PRESERVATION-VARMALA-015':
    'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'THREE-D-RESIN-009':
    'Two house nameplates side by side — one crisp 3D-printed, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'EDITORIAL-015': 'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PROCESS-CURE-008':
    'A studio workbench with a sketch, pigment swatches, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'GIFTS-008': 'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'GIFTS-009':
    'A premium Diwali corporate gift box with resin diyas and a gold-flecked tray, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'LARGEFORMAT-SIDE-003':
    'A tidy home-office desk with custom 3D-printed organizer, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'GIFTS-010': 'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'MATERIAL-MACRO-031':
    'A pristine resin ocean-wave art piece being dusted with a soft brush, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'EDITORIAL-016':
    'Lit tea-lights in ocean-blue resin holders with gold rims, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'THREE-D-RESIN-010':
    'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'DECOR-015': 'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'DECOR-016':
    'A curated flat-lay of varied resin gifts — bookmark, coaster, pendant, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'WALL-ART-020':
    'Playful premium kids-room resin decor — a cloud-and-stars name plaque and small night-light in soft azure blue resin with gentle gold accents, on a shelf. luxury product photography, handcrafted resin art.',
  'DECOR-017': 'Deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PRESERVATION-KEEPSAKE-003':
    'A wedding invitation card and dried rose petals suspended in a clear resin block keepsake, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'THREE-D-RESIN-011':
    'Close-up of three 3D-printing material samples — matte PLA, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'PRESERVATION-KEEPSAKE-004':
    "A baby's tiny handprint and footprint cast in a resin keepsake frame with a soft gold blank lettering area, deep ocean-blue resin tones, with metallic gold accents, soft studio light.",
  'THREE-D-RESIN-012':
    'A detailed 3D-printed architectural scale model of a modern building displayed on an executive desk, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'MATERIAL-MACRO-032':
    'A pair of sculptural handcrafted resin vases, ocean-blue translucent gradient with gold veining, one holding dried pampas stems, on a dark stone plinth. luxury product photography, handcrafted resin art.',
  'PROCESS-STUDIO-015':
    'A resin-art workshop scene — gloved artisan hands pouring glossy ocean-blue resin from a cup onto a mould, pigment jars and gold flake dishes on the workbench. luxury product photography, handcrafted resin art.',
  'MATERIAL-MACRO-033':
    'A luxurious oval vanity mirror framed in ocean-blue resin with gold leaf inclusions, standing on a dark dresser with soft reflected glow. luxury product photography, handcrafted resin art.',
  'THREE-D-RESIN-013':
    'An assortment of intricate 3D-printed gift objects — geometric lamp, custom figurine, deep ocean-blue resin tones, with metallic gold accents, soft studio light.',
  'LARGEFORMAT-DINING-004':
    'Vertical : a large live-edge resin dining table with a deep ocean blue epoxy river through natural walnut in a tall serene architectural interior, upper third calm..',
  'MATERIAL-MACRO-034': 'Gold leaf settling on sapphire resin (720p variant 2).',
  'DECOR-018':
    'Extreme macro: a bar of soft warm light sweeping across a deeply polished resin surface revealing mirror-gloss depth, pigment layers and wood grain below..',
  'PROCESS-TIMBER-006':
    'Extreme macro tracking along a live edge where teak grain meets clear resin, light shifting so resin flashes transparent to deep reflective..',
  'PROCESS-POUR-009':
    'Extreme slow-motion macro of deep sapphire resin pouring in one unbroken ribbon into a shallow round mould, single soft key from upper left, seamless 5s loop.',
  'PROCESS-STUDIO-016':
    "Dark premium artisan atelier: craftsman's hands only, no face, sanding the live edge of a resin and walnut tabletop, dust motes in one warm shaft of light..",
  'PROCESS-POUR-010':
    'Extreme macro slow-motion: liquid epoxy in deep sapphire pouring onto black glass, fine metallic gold pigment swirling in delicate veins, pitch-black studio, single soft key.',
  'PROCESS-POUR-011':
    'Extreme slow-motion macro of sapphire resin pouring in one unbroken ribbon into a wide shallow mould, matte black background.',
  'PROCESS-TIMBER-007':
    'Material story in one slow move: raw walnut grain, clear resin advancing across the timber edge and settling glassy, light sweeping once across the cured polished surface..',
  'EDITORIAL-017':
    'Vertical abstract background: ink-dark and deep ocean blue resin drifting in very slow folds, faint champagne light, top third calm as text safe area..',
  'EDITORIAL-018': 'Sapphire resin pour, high angle (720p variant 2).',
  'MATERIAL-MACRO-035':
    'Extreme macro of a curing resin surface resembling ocean waves from above: layered translucent sapphire and midnight blue with thin veins of shimmering gold leaf, light sweeping across.',
  'PROCESS-STUDIO-017': 'Workshop bench dolly (720p variant 2).',
  'PROCESS-STUDIO-018': 'Workshop bench dolly (720p variant).',
  'PROCESS-MOULD-012':
    'Artisan hands in a dark workshop at night pouring glossy blue resin from a steel cup into a round silicone mould, warm desk lamp only light.',
  'PROCESS-PIGMENT-012':
    'Extreme macro: mineral pigment dispersing through wet clear resin during a pour, slow blooming clouds of deep blue and white, one soft directional light, dark neutral background..',
  'PROCESS-PIGMENT-013':
    'Vertical macro for mobile: deep ocean blue resin flowing with white pigment veils blooming upward, upper third calm and dark as headline safe area..',
  'PROCESS-STUDIO-019':
    'Slow smooth dolly along a long workshop bench set with pour cups, pigment jars and curing moulds under warm pendant light.',
  'MATERIAL-MACRO-036':
    'Abstract slow background: deep ocean blue and ink-dark resin drifting in slow laminar folds, faint champagne-warm light, huge negative space., very slow.',
  'MATERIAL-MACRO-037':
    'Extreme slow-motion macro of champagne-gold leaf settling onto a wet sapphire resin surface, a single sheet drifting down and adhering as fine cracks of gold spread across the pool, matte black background.',
  'MATERIAL-MACRO-038':
    'Extreme macro of deep ocean blue resin flowing and folding like a sea seen from above, white pigment veils blooming.',
  'MATERIAL-MACRO-039': 'Gold leaf settling on sapphire resin (720p variant).',
  'EDITORIAL-019': 'Sapphire resin pour, high angle (720p variant).',
  'GALLERY-SCENE-005':
    'A polished rectangular resin art block standing in a dark gallery, very slow push-in, caustic light refracting through translucent blue resin onto the wall behind, gold flecks suspended inside.',
  'PROCESS-POUR-012':
    'Extreme slow-motion macro of deep sapphire epoxy pouring in one unbroken continuous ribbon into a shallow round mould on matte black, seamless 10s loop.',
  'LARGEFORMAT-DINING-005':
    'Slow dolly toward a large live-edge resin dining table, deep ocean blue epoxy river meeting natural walnut, serene architectural interior with tall windows and soft morning light..',
}
