import type { SeoLevel } from './resolve'

/**
 * The Coverage tab's arithmetic — pure, over rows the Studio (or the inventory builder) already
 * read. Every figure is a count of rows in a named state; none is a score, a rank or a claim.
 *
 *   derived            pages and entities whose title OR description resolved from the DERIVED rung
 *   missingDescription no rung supplied a description at all (GLOBAL excluded — it is a default,
 *                      not this page's)
 *   missingOgImage     no rung supplied a social image
 *   duplicateTitles    the same resolved title on more than one address
 *   noindexEntities    entities whose directive says noindex
 *   keywordsUnresearched themes still UNRESEARCHED — SEED §42's caveat as a number
 */

export type CoverageRow = {
  readonly path: string
  readonly kind: 'page' | 'entity'
  readonly title: string | null
  readonly titleLevel: SeoLevel
  readonly description: string | null
  readonly descriptionLevel: SeoLevel
  readonly ogMediaId: string | null
  readonly noindex: boolean
}

export type CoverageReport = {
  readonly total: number
  readonly pages: number
  readonly entities: number
  readonly derived: readonly string[]
  readonly missingDescription: readonly string[]
  readonly missingOgImage: readonly string[]
  readonly duplicateTitles: readonly { readonly title: string; readonly paths: readonly string[] }[]
  readonly noindexEntities: readonly string[]
  readonly keywordsUnresearched: number
  readonly keywordsTotal: number
}

export function coverageReport(
  rows: readonly CoverageRow[],
  keywords: readonly { readonly research_status: string }[],
): CoverageReport {
  // A title that came from the GLOBAL rung is "no title of its own", not a duplicate: the site
  // default is expected to repeat. Duplicates are counted among titles a rung above it supplied.
  const byTitle = new Map<string, string[]>()
  for (const row of rows) {
    if (row.title === null || row.titleLevel === 'GLOBAL') continue
    const key = row.title.trim().toLowerCase()
    byTitle.set(key, [...(byTitle.get(key) ?? []), row.path])
  }
  const duplicateTitles = [...byTitle.entries()]
    .filter(([, paths]) => paths.length > 1)
    .map(([title, paths]) => ({ title, paths: [...paths].sort() }))
    .sort((a, b) => a.title.localeCompare(b.title))

  return {
    total: rows.length,
    pages: rows.filter((row) => row.kind === 'page').length,
    entities: rows.filter((row) => row.kind === 'entity').length,
    derived: rows
      .filter((row) => row.titleLevel === 'DERIVED' || row.descriptionLevel === 'DERIVED')
      .map((row) => row.path),
    // The home page's description IS the site default by design (content/seed/seo.ts), so it is
    // the one address the GLOBAL rung counts as its own.
    missingDescription: rows
      .filter(
        (row) =>
          row.description === null || (row.descriptionLevel === 'GLOBAL' && row.path !== '/'),
      )
      .map((row) => row.path),
    missingOgImage: rows.filter((row) => row.ogMediaId === null).map((row) => row.path),
    duplicateTitles,
    noindexEntities: rows
      .filter((row) => row.kind === 'entity' && row.noindex)
      .map((row) => row.path),
    keywordsUnresearched: keywords.filter((row) => row.research_status === 'UNRESEARCHED').length,
    keywordsTotal: keywords.length,
  }
}

/** The report as the Markdown section the content inventory carries. Deterministic. */
export function coverageMarkdown(report: CoverageReport): string {
  const list = (paths: readonly string[]): string =>
    paths.length === 0 ? '—' : paths.map((path) => `\`${path}\``).join(', ')
  return [
    '## SEO coverage',
    '',
    '> GENERATED by the same run as the inventory above (`scripts/seo/build-seo-coverage.ts`).',
    '> Counts of rows in a named state; no figure here is a ranking, a volume or a claim.',
    '',
    `- **${String(report.total)}** addresses resolved (${String(report.pages)} pages, ${String(report.entities)} entities)`,
    `- **${String(report.derived.length)}** resolve a title or description from page content (DERIVED): ${list(report.derived)}`,
    `- **${String(report.missingDescription.length)}** have no description of their own: ${list(report.missingDescription)}`,
    `- **${String(report.missingOgImage.length)}** have no social image: ${list(report.missingOgImage)}`,
    `- **${String(report.duplicateTitles.length)}** titles are shared by more than one address${
      report.duplicateTitles.length === 0
        ? ''
        : ': ' + report.duplicateTitles.map((d) => `"${d.title}" (${list(d.paths)})`).join('; ')
    }`,
    `- **${String(report.noindexEntities.length)}** entities are \`noindex\`: ${list(report.noindexEntities)}`,
    `- **${String(report.keywordsUnresearched)}** of ${String(report.keywordsTotal)} keyword themes are still UNRESEARCHED — SEED §42: the strategy must be refined through research before claiming ranking opportunity`,
    '',
  ].join('\n')
}
