#!/usr/bin/env node
/**
 * demo:sql — print the demo seed as plain, idempotent SQL.
 *
 * WHY A SECOND WAY TO SEED. `demo:seed` needs a direct PostgreSQL connection (`DATABASE_URL`), and
 * the hosted project is reachable from some environments only through a SQL console — the Supabase
 * dashboard, or the MCP `execute_sql` tool this repository's phases are applied through. This
 * prints the same writes `demo:seed` makes, as literal SQL, so the demo catalogue can be replayed
 * where the seeder cannot connect. It reads the modules, not a database, and writes nothing.
 *
 * SAME RULES AS THE SEEDER, STATED IN THE SQL RATHER THAN IN CODE:
 *   - every row carries `is_demo`; `npm run demo:purge` (or its SQL twin, `--purge`) removes it;
 *   - a product, project or page whose slug is held by a NON-demo row is left alone
 *     (`where not exists (… and not is_demo)`), because the real thing replaces the placeholder
 *     and never the reverse;
 *   - categories are resolved by slug at replay time, never by a hard-coded id;
 *   - the article page walks DRAFT → REVIEW → APPROVED → PUBLISHED one edge at a time, exactly as
 *     `guard_stage_transition` requires, and only where the article is not
 *     OWNER_VERIFICATION_REQUIRED.
 *
 *   npm run demo:sql            # the seed, to stdout
 *   npm run demo:sql -- --purge # the purge, to stdout
 */
import { DEMO_ARTICLE_BODIES } from './articles'
import { DEMO_PRODUCTS } from './content'
import { DEMO_PROJECTS, DEMO_TESTIMONIALS } from './portfolio'

const purge = process.argv.includes('--purge')

/** A SQL string literal. Single quotes doubled; nothing else is special inside E''-less literals. */
const q = (value: string): string => `'${value.replace(/'/g, "''")}'`

const lines: string[] = []
const w = (line = ''): void => {
  lines.push(line)
}

if (purge) {
  w(
    '-- demo:purge as SQL. Removes every demo row and restores the two seeded statuses the seed changes.',
  )
  w('begin;')
  w(
    'update journal_articles a set page_id = null from pages p where p.id = a.page_id and p.is_demo;',
  )
  w('delete from page_sections where is_demo;')
  w('delete from pages where is_demo;')
  w('delete from products where is_demo;')
  w('delete from portfolio_projects where is_demo;')
  w('delete from testimonials where is_demo;')
  w("update categories set status = 'DRAFT' where seed_key is not null and status = 'PUBLISHED';")
  w('commit;')
} else {
  w(
    '-- demo:seed as SQL. Generated by scripts/demo/build-sql.ts from scripts/demo/*.ts; every row is_demo.',
  )
  w('begin;')
  w()
  w('-- 1. Publish the seeded categories the specification does not flag for owner verification.')
  w(
    "update categories set status = 'PUBLISHED', published_at = coalesce(published_at, now())\n" +
      "  where status = 'DRAFT' and seed_key is not null and owner_verification <> 'OWNER_VERIFICATION_REQUIRED';",
  )
  w()
  w(
    `-- 2. Products — ${String(DEMO_PRODUCTS.length)} rows, PRICE_ON_REQUEST, no dimension, no material.`,
  )
  for (const [index, product] of DEMO_PRODUCTS.entries()) {
    w(
      'insert into products (slug, title, subtitle, summary, description, category_id, price_state, availability_state,\n' +
        '  is_large_format, is_customizable, sort_order, status, owner_verification, fact_classification, is_demo, specifications_omitted)\n' +
        `select ${q(product.slug)}, ${q(product.title)}, ${q(product.subtitle)}, ${q(product.summary)}, ${q(product.description)},\n` +
        `  (select id from categories where slug = ${q(product.category)}), 'PRICE_ON_REQUEST', 'MADE_TO_ORDER',\n` +
        `  ${product.isLargeFormat === true ? 'true' : 'false'}, ${product.isCustomizable === true ? 'true' : 'false'}, ${String((index + 1) * 10)}, 'PUBLISHED', 'NOT_REQUIRED', 'EDITORIAL_COPY', true, true\n` +
        `where not exists (select 1 from products where slug = ${q(product.slug)} and not is_demo)\n` +
        'on conflict (slug) do update set title = excluded.title, subtitle = excluded.subtitle, summary = excluded.summary,\n' +
        '  description = excluded.description, category_id = excluded.category_id, is_large_format = excluded.is_large_format,\n' +
        '  is_customizable = excluded.is_customizable, sort_order = excluded.sort_order;',
    )
  }
  w()
  w(
    `-- 3. Article bodies — ${String(Object.keys(DEMO_ARTICLE_BODIES).length)} demo pages under the seeded journal articles.`,
  )
  for (const [slug, bands] of Object.entries(DEMO_ARTICLE_BODIES)) {
    const pageSlug = `journal-${slug}`
    w(
      `insert into pages (slug, path, kind, title, status, is_demo, fact_classification)\n` +
        `select ${q(pageSlug)}, ${q(`/journal/${slug}`)}, 'ARTICLE', ${q(slug)}, 'DRAFT', true, 'EDITORIAL_COPY'\n` +
        `where exists (select 1 from journal_articles where slug = ${q(slug)})\n` +
        `  and not exists (select 1 from pages where slug = ${q(pageSlug)} and not is_demo)\n` +
        'on conflict (slug) do update set title = excluded.title;',
    )
    w(
      `update journal_articles set page_id = (select id from pages where slug = ${q(pageSlug)} and is_demo)\n` +
        `  where slug = ${q(slug)} and exists (select 1 from pages where slug = ${q(pageSlug)} and is_demo);`,
    )
    w(
      `delete from page_sections where is_demo and page_id = (select id from pages where slug = ${q(pageSlug)} and is_demo);`,
    )
    for (const [position, band] of bands.entries()) {
      w(
        'insert into page_sections (page_id, block_type, position, is_visible, heading, body, status, is_demo, fact_classification)\n' +
          `select id, ${q(band.blockType)}, ${String(position + 1)}, true, ${q(band.heading)}, ${q(band.body)}, 'PUBLISHED', true, 'EDITORIAL_COPY'\n` +
          `  from pages where slug = ${q(pageSlug)} and is_demo;`,
      )
    }
    for (const [from, to] of [
      ['DRAFT', 'REVIEW'],
      ['REVIEW', 'APPROVED'],
      ['APPROVED', 'PUBLISHED'],
    ] as const) {
      w(
        `update pages p set status = '${to}', published_at = case when '${to}' = 'PUBLISHED' then coalesce(p.published_at, now()) else p.published_at end\n` +
          `  where p.slug = ${q(pageSlug)} and p.is_demo and p.status = '${from}'\n` +
          `    and exists (select 1 from journal_articles a where a.page_id = p.id and a.owner_verification <> 'OWNER_VERIFICATION_REQUIRED');`,
      )
    }
  }
  w()
  w(
    `-- 4. Portfolio projects — ${String(DEMO_PROJECTS.length)} rows, DRAFT; the evidence gate keeps them there.`,
  )
  for (const [index, project] of DEMO_PROJECTS.entries()) {
    w(
      'insert into portfolio_projects (slug, title, subtitle, summary, project_type, location_label, is_client_project, client_consent,\n' +
        '  sort_order, status, owner_verification, fact_classification, is_demo)\n' +
        `select ${q(project.slug)}, ${q(project.title)}, ${q(project.subtitle)}, ${q(project.summary)}, ${q(project.projectType)}, ${q(project.locationLabel)},\n` +
        `  false, 'NOT_APPLICABLE', ${String((index + 1) * 10)}, 'DRAFT', 'OWNER_VERIFICATION_REQUIRED', 'EDITORIAL_COPY', true\n` +
        `where not exists (select 1 from portfolio_projects where slug = ${q(project.slug)} and not is_demo)\n` +
        'on conflict (slug) do update set title = excluded.title, subtitle = excluded.subtitle, summary = excluded.summary,\n' +
        '  project_type = excluded.project_type, location_label = excluded.location_label, sort_order = excluded.sort_order;',
    )
  }
  w()
  w(
    `-- 5. Testimonials — ${String(DEMO_TESTIMONIALS.length)} rows, DRAFT, consent PENDING, attributed to a role and never a person.`,
  )
  for (const [index, testimonial] of DEMO_TESTIMONIALS.entries()) {
    w(
      'insert into testimonials (attributed_to, attribution_role, quote, consent, sort_order, status, owner_verification, fact_classification, is_demo)\n' +
        `select ${q(testimonial.attributedTo)}, ${q(testimonial.attributionRole)}, ${q(testimonial.quote)}, 'PENDING', ${String((index + 1) * 10)}, 'DRAFT', 'OWNER_VERIFICATION_REQUIRED', 'EDITORIAL_COPY', true\n` +
        `where not exists (select 1 from testimonials where quote = ${q(testimonial.quote)});`,
    )
  }
  w()
  w('commit;')
}

process.stdout.write(`${lines.join('\n')}\n`)
