#!/usr/bin/env node
/**
 * GENERATED: supabase/migrations/0052_phase08_transition_trigger.sql
 *
 * Emits `enforce_status_transition()` from `lib/cms/transitions.ts` and the permission matrix, so
 * the twelve edges exist in exactly one place.
 *
 * WHY GENERATE RATHER THAN HAND-WRITE. The state machine has two enforcers: `lib/cms/publishing.ts`
 * checks it before calling the database, and this trigger checks it inside. The TypeScript copy is
 * the one people read and edit; the SQL copy is the one an API caller actually hits, because
 * PostgREST is reachable with an anon key and a session cookie and never runs a line of our
 * TypeScript. Two hand-written copies of a state machine drift, and the copy that drifts silently
 * is always the one nobody opens — which here would be the only one that matters.
 *
 * `--check` re-renders and byte-compares, exactly as `auth:gen-role-sql` does. It runs in
 * `npm run check` and in CI as `cms:check-transitions`.
 *
 * Usage:
 *   npm run cms:gen-transitions
 *   npm run cms:check-transitions
 */
import { readFileSync, writeFileSync } from 'node:fs'

import { PERMISSION_ROLES } from '../../lib/auth/permissions'
import { TRANSITIONS, type ContentStatus } from '../../lib/cms/transitions'

const OUT = 'supabase/migrations/0052_phase08_transition_trigger.sql'

/** The six tables carrying a `content_status`. `content_revisions` has none — it records history. */
const GUARDED_TABLES = [
  'pages',
  'page_sections',
  'navigation_items',
  'global_content',
  'seo_entries',
  'faqs',
] as const

/** `'owner', 'admin'` — the literal list `has_role()` takes. */
function roleList(permission: string): string {
  const roles = PERMISSION_ROLES[permission as keyof typeof PERMISSION_ROLES]
  if (!roles) throw new Error(`unknown permission ${permission}`)
  return roles.map((r) => `'${r}'`).join(', ')
}

/** Statuses reachable from `from`, as a SQL array literal for the legality test. */
function reachable(from: ContentStatus): string {
  const to = TRANSITIONS.filter((t) => t.from === from).map((t) => `'${t.to}'`)
  return `array[${to.join(', ')}]::content_status[]`
}

const froms = [...new Set(TRANSITIONS.map((t) => t.from))]

function render(): string {
  const lines: string[] = []

  lines.push(`-- ${OUT.split('/').pop()} — Phase 08`)
  lines.push('--')
  lines.push(
    '-- GENERATED by scripts/cms/gen-transition-sql.ts from lib/cms/transitions.ts and the',
  )
  lines.push(
    '-- permission matrix. Do not edit. `npm run cms:check-transitions` fails the build if this',
  )
  lines.push('-- file and the TypeScript disagree.')
  lines.push('--')
  lines.push(
    '-- WHAT THIS TRIGGER IS FOR. lib/cms/publishing.ts checks the same rules before calling the',
  )
  lines.push(
    '-- database, and that check is the one that produces a good error message. This one exists',
  )
  lines.push(
    '-- because PostgREST is reachable with an anon key and a session cookie, and never runs a',
  )
  lines.push(
    '-- line of our TypeScript. Without it, a content.write holder can PATCH a row straight to',
  )
  lines.push("-- status='PUBLISHED' and reach the public site having never been in REVIEW.")
  lines.push('--')
  lines.push(
    '-- WHAT IT IS NOT FOR. The owner-verification gate is a CHECK constraint on each table',
  )
  lines.push('-- (`<table>_verified_before_publish`, migration 0050), not a branch here. A check')
  lines.push(
    '-- constraint has no INSERT hole and cannot be disabled per-session, and stating one rule',
  )
  lines.push(
    '-- in two enforcers is how the two come to disagree. The trigger owns exactly two things:',
  )
  lines.push('-- which edges exist, and who may take them.')
  lines.push('')
  lines.push('set search_path = public, extensions;')
  lines.push('')
  // A queryable form of the same edge list, so `cms_publish_section` can refuse an illegal move
  // with a readable message BEFORE it promotes any media — rather than promoting first and relying
  // on the trigger to roll the whole transaction back. Emitted from the same array, so the function
  // and the trigger cannot disagree.
  lines.push('create or replace function public.cms_transition_allowed(')
  lines.push('  p_from content_status,')
  lines.push('  p_to content_status')
  lines.push(')')
  lines.push('returns boolean')
  lines.push('language sql')
  lines.push('immutable')
  lines.push('set search_path = public, extensions')
  lines.push('as $$')
  lines.push(
    '  -- `from = to` is not a transition and is always allowed: an ordinary save must not',
  )
  lines.push('  -- need a status permission.')
  lines.push('  select p_from = p_to or (p_from, p_to) in (')
  lines.push(
    TRANSITIONS.map((t) => `    ('${t.from}'::content_status, '${t.to}'::content_status)`).join(
      ',\n',
    ),
  )
  lines.push('  );')
  lines.push('$$;')
  lines.push('')
  // 0022 narrowed EXECUTE on every public function to the roles that need it, after Supabase's
  // security advisor flagged the PostgreSQL default of granting EXECUTE to PUBLIC. A new function
  // that leaves the default in place quietly regresses that, and the advisor would flag it again.
  // This one is a pure predicate over two enum values and leaks nothing, but "harmless" is not the
  // standard the rest of the schema is held to.
  lines.push(
    'revoke execute on function public.cms_transition_allowed(content_status, content_status) from public, anon;',
  )
  lines.push(
    'grant execute on function public.cms_transition_allowed(content_status, content_status) to authenticated, service_role;',
  )
  lines.push('')
  lines.push('comment on function public.cms_transition_allowed(content_status, content_status) is')
  lines.push(
    `  'Generated from lib/cms/transitions.ts. The ${String(TRANSITIONS.length)} legal edges, queryable — so cms_publish_section can refuse before it writes.';`,
  )
  lines.push('')
  lines.push('create or replace function public.enforce_status_transition()')
  lines.push('returns trigger')
  lines.push('language plpgsql')
  lines.push('security invoker')
  lines.push('set search_path = public, extensions')
  lines.push('as $$')
  lines.push('declare')
  lines.push('  actor_role user_role := public.current_staff_role();')
  lines.push('begin')
  lines.push('  -- INSERT FIRST, because OLD is unassigned on INSERT. A leading')
  lines.push(
    '  -- `old.status is not distinct from new.status` short-circuit fails every insert into all',
  )
  lines.push(
    '  -- six tables at DML time rather than at CREATE time, which is a very confusing bug.',
  )
  lines.push('  if tg_op = ' + "'INSERT'" + ' then')
  lines.push(
    '    -- A null actor is the service role: a migration, or the Phase 09 seed runner over',
  )
  lines.push('    -- DATABASE_URL (A4·d). The seed legitimately writes global labels straight to')
  lines.push(
    '    -- PUBLISHED, so it is exempt from the DRAFT rule — but not from the check constraint',
  )
  lines.push('    -- that still refuses an unverified claim.')
  lines.push('    if actor_role is not null and new.status <> ' + "'DRAFT'" + ' then')
  lines.push('      raise exception')
  lines.push("        'a new % row must be created as DRAFT, not %', tg_table_name, new.status")
  lines.push("        using errcode = '23514',")
  lines.push("              constraint = 'content_status_transition',")
  lines.push(
    "              detail = 'constraint=content_status_transition; the generated insert policy has no status predicate, so this is what stops a content.write holder POSTing a PUBLISHED row straight to the public site';",
  )
  lines.push('    end if;')
  lines.push('    return new;')
  lines.push('  end if;')
  lines.push('')
  lines.push('  -- An ordinary edit. Not a transition, so nothing below applies.')
  lines.push('  if old.status is not distinct from new.status then')
  lines.push('    return new;')
  lines.push('  end if;')
  lines.push('')
  lines.push(
    '  -- 1. Does the edge exist at all? Asked before "may you", so an impossible move reads as',
  )
  lines.push('  --    impossible rather than as a permission problem.')
  lines.push('  case old.status')

  for (const from of froms) {
    lines.push(`    when '${from}' then`)
    lines.push(`      if not (new.status = any(${reachable(from)})) then`)
    lines.push('        raise exception')
    lines.push(
      "          'illegal status transition % -> % on %', old.status, new.status, tg_table_name",
    )
    lines.push("          using errcode = '23514',")
    lines.push("                constraint = 'content_status_transition',")
    lines.push("                detail = 'constraint=content_status_transition';")
    lines.push('      end if;')
  }
  lines.push('    else')
  lines.push('      raise exception')
  lines.push("        'no transitions are declared out of %', old.status")
  lines.push("        using errcode = '23514', constraint = 'content_status_transition';")
  lines.push('  end case;')
  lines.push('')
  lines.push(
    '  -- 2. May THIS actor take it? Only asked of a session actor; a null role is the service',
  )
  lines.push('  --    role, which ARCHITECTURE §4.2 says bypasses authorisation and not legality.')
  lines.push('  if actor_role is not null then')
  lines.push('    if not (')

  const clauses: string[] = []
  for (const t of TRANSITIONS) {
    clauses.push(
      `      (old.status = '${t.from}' and new.status = '${t.to}' and public.has_role(${roleList(t.permission)}))`,
    )
  }
  lines.push(clauses.join('\n      or\n'))
  lines.push('    ) then')
  lines.push('      raise exception')
  lines.push(
    "        'role % may not move % from % to %', actor_role, tg_table_name, old.status, new.status",
  )
  lines.push("        using errcode = '42501',")
  lines.push("              constraint = 'content_status_transition_permission',")
  lines.push("              detail = 'constraint=content_status_transition_permission';")
  lines.push('    end if;')
  lines.push('  end if;')
  lines.push('')
  lines.push('  return new;')
  lines.push('end;')
  lines.push('$$;')
  lines.push('')
  lines.push('comment on function public.enforce_status_transition() is')
  lines.push(
    `  'Generated from lib/cms/transitions.ts. ${String(TRANSITIONS.length)} edges. Owns edge legality and per-actor permission; the owner-verification gate is a CHECK constraint on each table.';`,
  )
  lines.push('')
  lines.push(
    'revoke execute on function public.enforce_status_transition() from public, anon, authenticated;',
  )
  lines.push('')

  for (const table of GUARDED_TABLES) {
    lines.push(`create trigger ${table}_enforce_status_transition`)
    lines.push(`  before insert or update on ${table}`)
    lines.push('  for each row execute function enforce_status_transition();')
    lines.push('')
  }

  // --------------------------------------------------------------------------------------------
  // owner_verification = VERIFIED needs content.verify — a rule no CHECK constraint can express,
  // because it is about WHO is writing, not what the row says.
  // --------------------------------------------------------------------------------------------
  lines.push(
    '-- --------------------------------------------------------------------------------------',
  )
  lines.push('-- enforce_verification_authority()')
  lines.push(
    '-- --------------------------------------------------------------------------------------',
  )
  lines.push('--')
  lines.push(
    '-- Setting owner_verification to VERIFIED asserts that a business claim is TRUE — that Rivya',
  )
  lines.push(
    '-- really does offer that service, really has that lead time. D10 exists because only the',
  )
  lines.push('-- owner can know that, so it takes content.verify rather than content.write.')
  lines.push('--')
  lines.push(
    '-- A CHECK constraint cannot express this: the rule is about the actor, and a constraint',
  )
  lines.push('-- sees only the row.')
  lines.push('create or replace function public.enforce_verification_authority()')
  lines.push('returns trigger')
  lines.push('language plpgsql')
  lines.push('security invoker')
  lines.push('set search_path = public, extensions')
  lines.push('as $$')
  lines.push('declare')
  lines.push('  actor_role user_role := public.current_staff_role();')
  lines.push('begin')
  lines.push('  if actor_role is null then')
  lines.push('    return new;')
  lines.push('  end if;')
  lines.push("  if new.owner_verification = 'VERIFIED'")
  lines.push(
    '     and (tg_op = ' +
      "'INSERT'" +
      ' or old.owner_verification is distinct from ' +
      "'VERIFIED'" +
      ')',
  )
  lines.push(`     and not public.has_role(${roleList('content.verify')}) then`)
  lines.push('    raise exception')
  lines.push("      'role % may not mark a % row VERIFIED', actor_role, tg_table_name")
  lines.push("      using errcode = '42501',")
  lines.push("            constraint = 'content_verification_authority',")
  lines.push("            detail = 'constraint=content_verification_authority';")
  lines.push('  end if;')
  lines.push('  return new;')
  lines.push('end;')
  lines.push('$$;')
  lines.push('')
  lines.push(
    'revoke execute on function public.enforce_verification_authority() from public, anon, authenticated;',
  )
  lines.push('')
  for (const table of GUARDED_TABLES) {
    lines.push(`create trigger ${table}_enforce_verification_authority`)
    lines.push(`  before insert or update on ${table}`)
    lines.push('  for each row execute function enforce_verification_authority();')
    lines.push('')
  }

  return lines.join('\n')
}

const rendered = render()
const check = process.argv.includes('--check')

if (check) {
  let existing: string
  try {
    existing = readFileSync(OUT, 'utf8')
  } catch {
    console.error(`✗ ${OUT} does not exist. Run: npm run cms:gen-transitions`)
    process.exit(1)
  }
  if (existing !== rendered) {
    console.error(
      `✗ ${OUT} does not match lib/cms/transitions.ts.\n` +
        '  The twelve edges live in the TypeScript; this file is rendered from them. Run\n' +
        '  `npm run cms:gen-transitions` and commit the result — do not edit the SQL by hand.',
    )
    process.exit(1)
  }
  console.log(`✓ ${OUT} matches lib/cms/transitions.ts (${String(TRANSITIONS.length)} edges)`)
} else {
  writeFileSync(OUT, rendered)
  console.log(
    `✓ wrote ${OUT} (${String(TRANSITIONS.length)} edges, ${String(GUARDED_TABLES.length)} tables)`,
  )
}
