import { afterAll, beforeAll, describe, expect, it } from 'vitest'

import { FIXTURE_USERS, asAnon, asSession, connect, disconnect } from './harness'

/**
 * Phase 20 at the table: what a stranger may write, and everything they may not read.
 *
 * THE MOST IMPORTANT ASSERTION IN THIS FILE IS A ZERO. `inquiries` carries a name, a phone number, a
 * city and whatever a visitor chose to say about their home, and it has no anon SELECT policy at
 * all. One `using (true)` — copied from another table, added to "let the visitor see their own
 * enquiry" — and the customer list is a GET away through PostgREST, with the publishable key that
 * ships in every browser. Nothing in TypeScript can catch that; this can.
 *
 * THE INSERT POLICY IS THE ONLY GUARD ON THE ONLY PUBLIC WRITE. D1 forbids customer accounts, so
 * there is no session to check and no permission to hold: the `with check` is doing the work
 * `requirePermission` does everywhere else, and each of the three columns it pins is tested here
 * with a payload that tries to set it.
 *
 * IT ALSO RECORDS THE `RETURNING` FINDING. PostgreSQL applies the SELECT policy to an INSERT's
 * RETURNING clause, so on this table the insert succeeds and the read-back is refused — with a
 * message that reads exactly like a rejected write and is not one. That behaviour is correct and
 * the write path is built around it (amendment A20); the test below is what stops somebody
 * "fixing" it with an anon select policy.
 */

const REQUIRE_DB = process.env.CI === 'true' || process.env.RLS_TESTS_REQUIRED === '1'
const HAVE_DB = Boolean(process.env.DATABASE_URL)

if (REQUIRE_DB && !HAVE_DB) {
  throw new Error(
    'DATABASE_URL is not set and this environment requires the database suite to run. ' +
      'Refusing to skip: a skipped guard suite reports success while proving nothing.',
  )
}

const describeDb = HAVE_DB ? describe : describe.skip

const asOwner = <T>(fn: Parameters<typeof asSession<T>>[2]) =>
  asSession('authenticated', FIXTURE_USERS.owner, fn)
const asResearcher = <T>(fn: Parameters<typeof asSession<T>>[2]) =>
  asSession('authenticated', FIXTURE_USERS.researcher, fn)

const ID = '00000000-0000-4000-8000-00000000e001'

/**
 * A COMMITTED FIXTURE, WRITTEN OUTSIDE THE HARNESS'S TRANSACTION.
 *
 * `asSession` wraps every block in `begin` … `rollback`, which is what keeps the suites independent
 * — and means nothing one block writes is visible to the next. A row that several blocks must SEE
 * therefore cannot be written by one of them. This uses the raw connection, as the superuser, so
 * the insert commits; RLS is bypassed by role attribute, which is fine because the fixture is not
 * what is under test. Every assertion about who may read it still runs inside a real session.
 */
async function seedInquiry(): Promise<void> {
  const db = await connect()
  await db.query(
    `insert into inquiries (id, kind, name, phone, city, message)
     values ($1, 'GENERAL', 'A Visitor', '+911234567890', 'Surat', 'A probe.')
     on conflict (id) do nothing`,
    [ID],
  )
}

async function cleanup(): Promise<void> {
  const db = await connect()
  await db.query(`delete from inquiries where id = $1`, [ID])
  await db.query(`delete from media_assets where public_id like 'rivya/inquiries/incoming/probe/%'`)
}

describeDb('inquiries — the one table a stranger may write', () => {
  beforeAll(async () => {
    await cleanup()
    await seedInquiry()
  })
  afterAll(cleanup)

  it('lets anon insert an enquiry', async () => {
    const result = await asAnon((sql) =>
      sql.attempt(
        `insert into inquiries (id, kind, name, phone, city, message)
         values ($1, 'GENERAL', 'A Visitor', '+911234567890', 'Surat', 'A probe.')`,
        // A different id: the harness rolls this session back, so the insert proves the policy
        // admits it and leaves nothing behind.
        ['00000000-0000-4000-8000-00000000e009'],
      ),
    )
    expect(result.ok, result.error).toBe(true)
  })

  /** The zero this file exists for. */
  it('lets anon read NOTHING — not even the row it just wrote', async () => {
    const rows = await asAnon((sql) => sql.rows(`select id from inquiries`))
    expect(rows).toHaveLength(0)

    const mine = await asAnon((sql) => sql.rows(`select id from inquiries where id = $1`, [ID]))
    expect(mine).toHaveLength(0)
  })

  /**
   * The finding that shaped the write path. The INSERT above succeeded; adding RETURNING to it does
   * not, because the SELECT policy applies to the returned row. The error even reads like a
   * rejected write. `inquiry_reference_code()` exists because of this.
   */
  it('refuses INSERT ... RETURNING for anon, which is why the id is generated by the caller', async () => {
    const result = await asAnon((sql) =>
      sql.attempt(
        `insert into inquiries (kind, name, phone) values ('GENERAL', 'B', '+911111111111')
         returning reference_code`,
      ),
    )
    expect(result.ok).toBe(false)
  })

  it('hands anon the reference code of a fresh enquiry, and only through the function', async () => {
    const rows = await asAnon((sql) =>
      sql.rows<{ code: string | null }>(`select public.inquiry_reference_code($1) as code`, [ID]),
    )
    expect(rows[0]?.code).toMatch(/^RIV-\d{4}-\d{6,}$/)
  })

  it('refuses an enquiry that arrives pre-triaged', async () => {
    const result = await asAnon((sql) =>
      sql.attempt(
        `insert into inquiries (kind, name, phone, pipeline_status)
         values ('GENERAL', 'Forger', '+911111111111', 'WON')`,
      ),
    )
    expect(result.ok).toBe(false)
  })

  it('refuses an enquiry that assigns itself to a member of staff', async () => {
    const result = await asAnon((sql) =>
      sql.attempt(
        `insert into inquiries (kind, name, phone, assigned_to)
         values ('GENERAL', 'Forger', '+911111111111', $1)`,
        [FIXTURE_USERS.owner],
      ),
    )
    expect(result.ok).toBe(false)
  })

  it('refuses an enquiry that claims a member of staff edited it', async () => {
    const result = await asAnon((sql) =>
      sql.attempt(
        `insert into inquiries (kind, name, phone, updated_by)
         values ('GENERAL', 'Forger', '+911111111111', $1)`,
        [FIXTURE_USERS.owner],
      ),
    )
    expect(result.ok).toBe(false)
  })

  it('refuses an enquiry that claims it has already been handed off', async () => {
    const result = await asAnon((sql) =>
      sql.attempt(
        `insert into inquiries (kind, name, phone, whatsapp_state)
         values ('GENERAL', 'Forger', '+911111111111', 'REDIRECTED')`,
      ),
    )
    expect(result.ok).toBe(false)
  })

  /**
   * The reference code is allocated by a trigger that OVERWRITES what arrived. A code a caller could
   * choose is a code a caller could collide with, enumerate, or use to claim somebody else's
   * enquiry in a WhatsApp message.
   */
  it('discards a reference code the caller supplied', async () => {
    // Written and read in ONE owner session, because the harness rolls each session back and the
    // owner holds `inquiries.write`, so the same policy path a merchandiser uses is exercised.
    const rows = await asOwner(async (sql) => {
      await sql.rows(
        `insert into inquiries (id, kind, name, phone, reference_code)
         values ($1, 'GENERAL', 'C', '+911111111111', 'RIV-1999-000001')`,
        ['00000000-0000-4000-8000-00000000e002'],
      )
      return sql.rows<{ reference_code: string }>(
        `select reference_code from inquiries where id = $1`,
        ['00000000-0000-4000-8000-00000000e002'],
      )
    })
    expect(rows[0]?.reference_code).not.toBe('RIV-1999-000001')
  })

  /**
   * `table-permissions.ts` used this table as its worked example before it existed: a
   * `using (is_staff())` copied onto `inquiries` would hand every customer's phone number to a role
   * whose entire remit is looking at competitors.
   */
  it('hides every enquiry from the researcher, who does not hold inquiries.read', async () => {
    const rows = await asResearcher((sql) => sql.rows(`select id from inquiries`))
    expect(rows).toHaveLength(0)
  })

  it('shows enquiries to the owner, who does', async () => {
    const rows = await asOwner((sql) => sql.rows(`select id from inquiries where id = $1`, [ID]))
    expect(rows).toHaveLength(1)
  })
})

describeDb('the enquiry timeline', () => {
  beforeAll(seedInquiry)
  afterAll(cleanup)

  it('records CREATED in the inserting transaction', async () => {
    const rows = await asOwner((sql) =>
      sql.rows<{ event: string }>(
        `select event from inquiry_events where inquiry_id = $1 order by occurred_at`,
        [ID],
      ),
    )
    expect(rows.map((row) => row.event)).toContain('CREATED')
  })

  /**
   * TWO LAYERS, AND THEY FAIL DIFFERENTLY — which is why this is two assertions rather than one.
   *
   * For the OWNER there is no UPDATE policy, so RLS FILTERS the statement: it matches no rows,
   * affects none, and RAISES NOTHING. That is the ordinary shape of an RLS refusal and the reason
   * every write in the repository layer reads its row back.
   *
   * For `service_role`, which bypasses RLS by role attribute, the statement reaches the row — and
   * the trigger refuses it outright. Without that second layer, a service-role client or a future
   * migration could rewrite the timeline with nothing to stop it.
   */
  it('cannot be edited by the owner, because no policy admits it', async () => {
    const updated = await asOwner((sql) =>
      sql.affectedRows(`update inquiry_events set note = 'rewritten' where inquiry_id = $1`, [ID]),
    )
    expect(updated).toBe(0)

    const deleted = await asOwner((sql) =>
      sql.affectedRows(`delete from inquiry_events where inquiry_id = $1`, [ID]),
    )
    expect(deleted).toBe(0)
  })

  it('cannot be edited even by a client that bypasses RLS, because the trigger refuses', async () => {
    const updated = await asSession('service_role', undefined, (sql) =>
      sql.attempt(`update inquiry_events set note = 'rewritten' where inquiry_id = $1`, [ID]),
    )
    expect(updated.ok).toBe(false)
    expect(updated.error).toMatch(/append-only/i)

    const deleted = await asSession('service_role', undefined, (sql) =>
      sql.attempt(`delete from inquiry_events where inquiry_id = $1`, [ID]),
    )
    expect(deleted.ok).toBe(false)
  })

  it('is invisible to anon', async () => {
    const rows = await asAnon((sql) => sql.rows(`select id from inquiry_events`))
    expect(rows).toHaveLength(0)
  })
})

describeDb('attaching a visitor’s references', () => {
  beforeAll(seedInquiry)
  afterAll(cleanup)

  it('refuses a public_id outside the folder the upload endpoint signs', async () => {
    const attached = await asAnon((sql) =>
      sql.rows<{ attached: number }>(
        `select public.attach_inquiry_references($1, $2::jsonb) as attached`,
        [ID, JSON.stringify([{ publicId: 'rivya/brand/logo', filename: 'logo.png' }])],
      ),
    )
    expect(attached[0]?.attached).toBe(0)
  })

  /**
   * Called and read in ONE session, because the harness rolls each one back. The function is
   * SECURITY DEFINER, so which role calls it changes nothing about what it does — and that it is
   * callable by `anon` at all is asserted in `function-grants.test.ts`, where the allowlist lives.
   */
  it('attaches one inside it, as a USER_UPLOAD draft', async () => {
    const rows = await asSession('service_role', undefined, async (sql) => {
      await sql.rows(`select public.attach_inquiry_references($1, $2::jsonb)`, [
        ID,
        JSON.stringify([
          { publicId: 'rivya/inquiries/incoming/probe/photo', filename: 'photo.jpg' },
        ]),
      ])
      return sql.rows<{ source: string; status: string }>(
        `select m.source, m.status from inquiry_attachments a
           join media_assets m on m.id = a.media_asset_id
          where a.inquiry_id = $1`,
        [ID],
      )
    })
    expect(rows).toHaveLength(1)
    expect(rows[0]?.source).toBe('USER_UPLOAD')
    expect(rows[0]?.status).toBe('DRAFT')
  })
})

describeDb('recording the handoff', () => {
  beforeAll(seedInquiry)
  afterAll(cleanup)

  it('writes the two columns once and refuses to write them twice', async () => {
    const result = await asSession('service_role', undefined, async (sql) => {
      const first = await sql.rows<{ ok: boolean }>(
        `select public.record_inquiry_handoff($1, 'SHORTENED', 3) as ok`,
        [ID],
      )
      const second = await sql.rows<{ ok: boolean }>(
        `select public.record_inquiry_handoff($1, 'REDIRECTED', null) as ok`,
        [ID],
      )
      const row = await sql.rows<{
        whatsapp_state: string
        whatsapp_shortened_at_level: number
      }>(`select whatsapp_state, whatsapp_shortened_at_level from inquiries where id = $1`, [ID])
      return { first: first[0]?.ok, second: second[0]?.ok, row: row[0] }
    })

    expect(result.first).toBe(true)
    // The second call finds the row already handed off and reports it rather than overwriting: a
    // bookkeeping call that ran twice must not turn SHORTENED into REDIRECTED.
    expect(result.second).toBe(false)
    expect(result.row?.whatsapp_state).toBe('SHORTENED')
    expect(result.row?.whatsapp_shortened_at_level).toBe(3)
  })

  it('gives anon no UPDATE on inquiries by any other route', async () => {
    const result = await asAnon((sql) =>
      sql.affectedRows(`update inquiries set phone = '+910000000000' where id = $1`, [ID]),
    )
    // RLS FILTERS an update rather than refusing it: no policy means no rows matched.
    expect(result).toBe(0)
  })
})
