-- 0012_audit_logs.sql — Phase 04
--
-- The append-only record of every privileged mutation AND every denial.
--
-- Denials matter as much as successes: a log that records only what succeeded cannot show you
-- someone probing for what they cannot reach. withPermission() writes result = 'DENIED' before
-- throwing, so a refused action is evidence rather than silence.
--
-- WHY THERE IS NO `authenticated` INSERT POLICY
-- --------------------------------------------
-- An insert policy would let any signed-in staff member write entries in the security log —
-- including entries implicating somebody else, or a wall of noise to bury their own. The only
-- writer is lib/auth/audit.ts through the service-role client, which bypasses RLS by role
-- attribute. DATA_MODEL §1.5 already specifies RLS-APPEND as "insert by trigger or service role";
-- the phase document's revoke line left insert ambiguous, and this resolves it to the safer
-- reading (amendment A5·b).
--
-- The revoke below is the other half, and it is only meaningful because the local shim reproduces
-- Supabase's grants: on Supabase, `authenticated` holds UPDATE and DELETE on every table in public
-- by default, so revoking them is a real removal. Without those grants the revoke is a no-op and a
-- test of it proves nothing.
--
-- This table is exempt from the D5 content columns (DATA_MODEL §1.4): it is an immutable
-- operational record, and a content_status on it would imply a publication workflow.

set search_path = public, extensions;

create table audit_logs (
  id             uuid primary key default gen_random_uuid(),
  occurred_at    timestamptz not null default now(),

  -- Who. Nullable because a denial can happen before a session resolves to a staff member, and
  -- recording "someone unauthenticated tried this" is more useful than recording nothing.
  actor_user_id  uuid references auth.users(id) on delete set null,
  actor_role     user_role,

  -- What. `action` is a dotted verb ('catalog.product.publish'); entity_type/entity_id name the
  -- target so the log can be read per record without parsing the summary.
  action         text not null,
  entity_type    text,
  entity_id      uuid,
  summary        text,

  -- The change. Both pass through lib/logging/redact.ts before they reach here: never a token, a
  -- key, a password, a raw visitor IP for a public form, a WhatsApp message body, or inquiry free
  -- text. A security log that accumulates secrets is a second copy of the thing it protects.
  "before"       jsonb,
  "after"        jsonb,

  result         text not null,

  -- Correlation. `ip` is inet rather than text so it can be reasoned about as an address.
  request_id     text,
  ip             inet,
  user_agent     text,

  constraint audit_logs_result_allowed check (result in ('SUCCESS', 'DENIED', 'ERROR')),
  constraint audit_logs_action_present check (length(btrim(action)) > 0)
);

-- Reading the log is almost always "most recent first", optionally narrowed to one actor or one
-- record. Denials are the security question, so they get a partial index of their own.
create index audit_logs_occurred_idx on audit_logs (occurred_at desc);
create index audit_logs_actor_idx on audit_logs (actor_user_id, occurred_at desc);
create index audit_logs_entity_idx on audit_logs (entity_type, entity_id, occurred_at desc);
create index audit_logs_denied_idx on audit_logs (occurred_at desc) where result = 'DENIED';

alter table audit_logs enable row level security;

-- ------------------------------------------------------------------------------------------------
-- audit_logs — shape C
-- ------------------------------------------------------------------------------------------------
-- DECLARED DEVIATION. Append-only security log. No anon policy, no authenticated write policy of
-- any kind, and update/delete are revoked outright so no session can rewrite history. Only the
-- service role writes, via lib/auth/audit.ts.
--
-- read: operations.audit.read (owner, admin)
--
-- The role list here is NOT generated by auth:gen-policies — that generator owns 0011, and this
-- table is created in this migration. scripts/auth/check-rls.ts still enforces the equality by
-- reading pg_policies back out of the live database, so the rule holds either way. If
-- operations.audit.read ever changes hands, check-rls fails and points here.

create policy audit_logs_select_staff on audit_logs for select
  to authenticated using (public.has_role('owner','admin'));

-- No insert, update or delete policy for authenticated. See the header.

-- Append-only, enforced by privilege rather than by policy. A policy can be added later by anyone
-- who can write a migration; a revoked privilege has to be granted back explicitly and visibly.
revoke update, delete on audit_logs from authenticated, anon;

comment on table audit_logs is
  'Append-only record of privileged mutations and denials. Written only by the service role; update and delete are revoked.';
comment on column audit_logs.result is
  'SUCCESS, DENIED or ERROR. DENIED rows are how probing becomes visible — they are the point, not a side effect.';
