-- 0052_phase08_transition_trigger.sql — Phase 08
--
-- GENERATED by scripts/cms/gen-transition-sql.ts from lib/cms/transitions.ts and the
-- permission matrix. Do not edit. `npm run cms:check-transitions` fails the build if this
-- file and the TypeScript disagree.
--
-- WHAT THIS TRIGGER IS FOR. lib/cms/publishing.ts checks the same rules before calling the
-- database, and that check is the one that produces a good error message. This one exists
-- because PostgREST is reachable with an anon key and a session cookie, and never runs a
-- line of our TypeScript. Without it, a content.write holder can PATCH a row straight to
-- status='PUBLISHED' and reach the public site having never been in REVIEW.
--
-- WHAT IT IS NOT FOR. The owner-verification gate is a CHECK constraint on each table
-- (`<table>_verified_before_publish`, migration 0050), not a branch here. A check
-- constraint has no INSERT hole and cannot be disabled per-session, and stating one rule
-- in two enforcers is how the two come to disagree. The trigger owns exactly two things:
-- which edges exist, and who may take them.

set search_path = public, extensions;

create or replace function public.enforce_status_transition()
returns trigger
language plpgsql
security invoker
set search_path = public, extensions
as $$
declare
  actor_role user_role := public.current_staff_role();
begin
  -- INSERT FIRST, because OLD is unassigned on INSERT. A leading
  -- `old.status is not distinct from new.status` short-circuit fails every insert into all
  -- six tables at DML time rather than at CREATE time, which is a very confusing bug.
  if tg_op = 'INSERT' then
    -- A null actor is the service role: a migration, or the Phase 09 seed runner over
    -- DATABASE_URL (A4·d). The seed legitimately writes global labels straight to
    -- PUBLISHED, so it is exempt from the DRAFT rule — but not from the check constraint
    -- that still refuses an unverified claim.
    if actor_role is not null and new.status <> 'DRAFT' then
      raise exception
        'a new % row must be created as DRAFT, not %', tg_table_name, new.status
        using errcode = '23514',
              constraint = 'content_status_transition',
              detail = 'constraint=content_status_transition; the generated insert policy has no status predicate, so this is what stops a content.write holder POSTing a PUBLISHED row straight to the public site';
    end if;
    return new;
  end if;

  -- An ordinary edit. Not a transition, so nothing below applies.
  if old.status is not distinct from new.status then
    return new;
  end if;

  -- 1. Does the edge exist at all? Asked before "may you", so an impossible move reads as
  --    impossible rather than as a permission problem.
  case old.status
    when 'DRAFT' then
      if not (new.status = any(array['REVIEW', 'ARCHIVED']::content_status[])) then
        raise exception
          'illegal status transition % -> % on %', old.status, new.status, tg_table_name
          using errcode = '23514',
                constraint = 'content_status_transition',
                detail = 'constraint=content_status_transition';
      end if;
    when 'REVIEW' then
      if not (new.status = any(array['DRAFT', 'APPROVED', 'ARCHIVED']::content_status[])) then
        raise exception
          'illegal status transition % -> % on %', old.status, new.status, tg_table_name
          using errcode = '23514',
                constraint = 'content_status_transition',
                detail = 'constraint=content_status_transition';
      end if;
    when 'APPROVED' then
      if not (new.status = any(array['PUBLISHED', 'REVIEW', 'DRAFT', 'ARCHIVED']::content_status[])) then
        raise exception
          'illegal status transition % -> % on %', old.status, new.status, tg_table_name
          using errcode = '23514',
                constraint = 'content_status_transition',
                detail = 'constraint=content_status_transition';
      end if;
    when 'PUBLISHED' then
      if not (new.status = any(array['DRAFT', 'ARCHIVED']::content_status[])) then
        raise exception
          'illegal status transition % -> % on %', old.status, new.status, tg_table_name
          using errcode = '23514',
                constraint = 'content_status_transition',
                detail = 'constraint=content_status_transition';
      end if;
    when 'ARCHIVED' then
      if not (new.status = any(array['DRAFT']::content_status[])) then
        raise exception
          'illegal status transition % -> % on %', old.status, new.status, tg_table_name
          using errcode = '23514',
                constraint = 'content_status_transition',
                detail = 'constraint=content_status_transition';
      end if;
    else
      raise exception
        'no transitions are declared out of %', old.status
        using errcode = '23514', constraint = 'content_status_transition';
  end case;

  -- 2. May THIS actor take it? Only asked of a session actor; a null role is the service
  --    role, which ARCHITECTURE §4.2 says bypasses authorisation and not legality.
  if actor_role is not null then
    if not (
      (old.status = 'DRAFT' and new.status = 'REVIEW' and public.has_role('owner', 'admin', 'editor'))
      or
      (old.status = 'DRAFT' and new.status = 'ARCHIVED' and public.has_role('owner', 'admin', 'editor'))
      or
      (old.status = 'REVIEW' and new.status = 'DRAFT' and public.has_role('owner', 'admin', 'editor'))
      or
      (old.status = 'REVIEW' and new.status = 'APPROVED' and public.has_role('owner', 'admin', 'editor'))
      or
      (old.status = 'REVIEW' and new.status = 'ARCHIVED' and public.has_role('owner', 'admin', 'editor'))
      or
      (old.status = 'APPROVED' and new.status = 'PUBLISHED' and public.has_role('owner', 'admin', 'editor'))
      or
      (old.status = 'APPROVED' and new.status = 'REVIEW' and public.has_role('owner', 'admin', 'editor'))
      or
      (old.status = 'APPROVED' and new.status = 'DRAFT' and public.has_role('owner', 'admin', 'editor'))
      or
      (old.status = 'APPROVED' and new.status = 'ARCHIVED' and public.has_role('owner', 'admin', 'editor'))
      or
      (old.status = 'PUBLISHED' and new.status = 'DRAFT' and public.has_role('owner', 'admin', 'editor'))
      or
      (old.status = 'PUBLISHED' and new.status = 'ARCHIVED' and public.has_role('owner', 'admin', 'editor'))
      or
      (old.status = 'ARCHIVED' and new.status = 'DRAFT' and public.has_role('owner', 'admin', 'editor'))
    ) then
      raise exception
        'role % may not move % from % to %', actor_role, tg_table_name, old.status, new.status
        using errcode = '42501',
              constraint = 'content_status_transition_permission',
              detail = 'constraint=content_status_transition_permission';
    end if;
  end if;

  return new;
end;
$$;

comment on function public.enforce_status_transition() is
  'Generated from lib/cms/transitions.ts. 12 edges. Owns edge legality and per-actor permission; the owner-verification gate is a CHECK constraint on each table.';

revoke execute on function public.enforce_status_transition() from public, anon, authenticated;

create trigger pages_enforce_status_transition
  before insert or update on pages
  for each row execute function enforce_status_transition();

create trigger page_sections_enforce_status_transition
  before insert or update on page_sections
  for each row execute function enforce_status_transition();

create trigger navigation_items_enforce_status_transition
  before insert or update on navigation_items
  for each row execute function enforce_status_transition();

create trigger global_content_enforce_status_transition
  before insert or update on global_content
  for each row execute function enforce_status_transition();

create trigger seo_entries_enforce_status_transition
  before insert or update on seo_entries
  for each row execute function enforce_status_transition();

create trigger faqs_enforce_status_transition
  before insert or update on faqs
  for each row execute function enforce_status_transition();

-- --------------------------------------------------------------------------------------
-- enforce_verification_authority()
-- --------------------------------------------------------------------------------------
--
-- Setting owner_verification to VERIFIED asserts that a business claim is TRUE — that Rivya
-- really does offer that service, really has that lead time. D10 exists because only the
-- owner can know that, so it takes content.verify rather than content.write.
--
-- A CHECK constraint cannot express this: the rule is about the actor, and a constraint
-- sees only the row.
create or replace function public.enforce_verification_authority()
returns trigger
language plpgsql
security invoker
set search_path = public, extensions
as $$
declare
  actor_role user_role := public.current_staff_role();
begin
  if actor_role is null then
    return new;
  end if;
  if new.owner_verification = 'VERIFIED'
     and (tg_op = 'INSERT' or old.owner_verification is distinct from 'VERIFIED')
     and not public.has_role('owner', 'admin') then
    raise exception
      'role % may not mark a % row VERIFIED', actor_role, tg_table_name
      using errcode = '42501',
            constraint = 'content_verification_authority',
            detail = 'constraint=content_verification_authority';
  end if;
  return new;
end;
$$;

revoke execute on function public.enforce_verification_authority() from public, anon, authenticated;

create trigger pages_enforce_verification_authority
  before insert or update on pages
  for each row execute function enforce_verification_authority();

create trigger page_sections_enforce_verification_authority
  before insert or update on page_sections
  for each row execute function enforce_verification_authority();

create trigger navigation_items_enforce_verification_authority
  before insert or update on navigation_items
  for each row execute function enforce_verification_authority();

create trigger global_content_enforce_verification_authority
  before insert or update on global_content
  for each row execute function enforce_verification_authority();

create trigger seo_entries_enforce_verification_authority
  before insert or update on seo_entries
  for each row execute function enforce_verification_authority();

create trigger faqs_enforce_verification_authority
  before insert or update on faqs
  for each row execute function enforce_verification_authority();
