-- ============================================================================================
-- 0280 — Phase 30: Large-Format Research Workspace
--
-- SEED §56 PUTS LARGE-FORMAT FURNITURE FIRST IN THE CONTENT HIERARCHY, and this phase gives the
-- same priority to research: a workspace over the subset of scraped rows that are large by a
-- STATED, EDITABLE rule.
--
-- THE ONE DECISION EVERYTHING ELSE FOLLOWS FROM: `is_large_format` IS THREE-VALUED.
--
-- True, false, and NULL meaning "we could not tell". That is not defensiveness, it is the only
-- honest encoding available. A row whose dimensions could not be parsed is not a small table — it
-- is a row we have no measurements for, and the difference matters at every reader. A boolean
-- would force that row to false, and every distribution, every count and every chart built on the
-- column would then quietly under-report large work in proportion to how badly the source's pages
-- are written. The failure would look like a finding.
--
-- So rule 10 sends an unparsed row to `UNKNOWN` before any threshold is applied, `is_large_format`
-- stays null, and every panel in the workspace renders the unknown bucket beside the other two.
--
-- `longest_axis_mm` IS WRITTEN BY THE CLASSIFIER, NOT GENERATED BY THE DATABASE, and the reason is
-- the override. A generated column cannot be written, and a researcher correcting a
-- misclassification has to be able to. The classifier derives it from `dimensions_mm` on every
-- pass; `scripts/research/reclassify-scale.ts` re-derives it offline over stored rows.
--
-- NOTHING HERE IS `research.confirm` WORK. A scale band is a CLASSIFICATION — it says what kind of
-- object a page describes — and carries no disposition meaning at all. The Phase 04 split puts it
-- with the normalised values: `research.write`, the operating half. This phase writes no
-- `disposition`, no `duplicate_of_id` and no `stage`.
--
-- AND NOTHING HERE IS PUBLIC. `research_products.is_large_format` and `products.is_large_format`
-- are different columns in different worlds; nothing joins them, and the isolation guard proves it.
-- The band vocabulary borrows the NAMES of the `largeformat-*` Higgsfield families so that a
-- merchandiser reads one set of words across the whole system — it borrows none of their assets,
-- and no band token may appear on a public surface.
-- ============================================================================================

set search_path = public, extensions;

-- --- 1. The classification, on the row it classifies ---------------------------------------------

alter table research_products
  /*
   * THE BAND VOCABULARY IS RIVYA'S OWN, DELIBERATELY.
   *
   * These are the `largeformat-*` manifest family names. A merchandiser who has spent a year
   * calling something a console table should not have to learn a second word for it because the
   * research subsystem invented one — and a vocabulary that matches across the system is what lets
   * a person move between the Higgsfield library, the public Large Format experience and this
   * workspace without translating.
   *
   * `UNKNOWN` IS A MEMBER OF THE LIST RATHER THAN A NULL, because it is a real answer. A null band
   * would be indistinguishable from "not classified yet", and the two need different treatment:
   * one is a row the rules have judged and cannot place, the other is a row nothing has looked at.
   * `classified_at` separates them.
   */
  add column scale_band text
    check (scale_band in ('DINING', 'CONSOLE', 'COFFEE', 'SEATING', 'SIDE', 'MONUMENTAL',
                          'WALL', 'UNKNOWN')),

  -- THREE-VALUED. See the header: null is "could not tell", and it is the commonest answer on a
  -- corpus of other people's web pages.
  add column is_large_format boolean,

  -- Derived from `dimensions_mm` by the classifier. Null whenever the dimensions are not PARSED.
  add column longest_axis_mm integer
    check (longest_axis_mm is null or (longest_axis_mm > 0 and longest_axis_mm <= 100000)),

  /*
   * WHO SAID SO, AND IT IS THE COLUMN THAT MAKES AN OVERRIDE SURVIVE.
   *
   * `EDITOR` freezes the row: the reclassification pass skips it and reports it as skipped, so a
   * researcher's judgement is not silently rewritten the next time somebody tunes a threshold.
   * That is the same promise `normalized_overrides` makes about a corrected price, and it is made
   * the same way — by recording the provenance rather than by hoping nobody re-runs anything.
   */
  add column large_format_source text
    check (large_format_source in ('RULE', 'EDITOR', 'UNKNOWN')),

  add column classified_at timestamptz,
  add column classified_rule_id uuid,

  -- A CLASSIFIED ROW NAMES WHAT CLASSIFIED IT. A band with no source is a value whose provenance
  -- nobody can establish, which is exactly what the override column exists to prevent.
  add constraint research_products_classification_is_attributed
    check ((scale_band is null and large_format_source is null and classified_at is null)
        or (scale_band is not null and large_format_source is not null and classified_at is not null)),

  /*
   * NO MEASUREMENT, NO VERDICT — AND THE TEST IS THE MEASUREMENT, NOT THE BAND.
   *
   * A first version of this constraint tied the null verdict to `scale_band = 'UNKNOWN'`, and that
   * was wrong in a way worth recording: a well-measured 1 150 mm piece whose proportions match no
   * band signature is banded `UNKNOWN` and its SIZE is perfectly well known. Refusing it a verdict
   * would move a confident answer into the bucket reserved for unanswerable ones, which is exactly
   * the dishonesty the three-valued column exists to prevent.
   *
   * What is actually invariant: a row with no `longest_axis_mm` has nothing to judge, so it may not
   * carry a verdict. `lib/scraper/analytics/scale.ts` says the same thing in the classifier.
   */
  add constraint research_products_unmeasured_has_no_verdict
    check (longest_axis_mm is not null or is_large_format is null);

comment on column research_products.is_large_format is
  'THREE-VALUED: true, false, or null meaning the dimensions could not be parsed. A boolean would force an unmeasurable row to false and make every distribution under-report large work in proportion to how badly a source writes its pages. Never joined to products.is_large_format, which is a different column in a different world.';
comment on column research_products.scale_band is
  'DINING, CONSOLE, COFFEE, SEATING, SIDE, MONUMENTAL, WALL or UNKNOWN. Rivya''s own largeformat-* vocabulary, so one set of words reads across the system. A research classification: it never appears on a public surface.';
comment on column research_products.large_format_source is
  'RULE, EDITOR or UNKNOWN. EDITOR freezes the row against reclassification — a researcher''s judgement is not rewritten when somebody tunes a threshold.';
comment on column research_products.longest_axis_mm is
  'Written by lib/scraper/analytics/scale.ts from dimensions_mm, not generated by the database: a generated column cannot be written, and an override has to be possible.';

-- The workspace's own query: the large rows of one source, by band.
create index research_products_scale_idx
  on research_products (is_large_format, scale_band, source_id);
-- The scatter reads parsed rows by longest axis.
create index research_products_longest_axis_idx
  on research_products (longest_axis_mm)
  where longest_axis_mm is not null;

-- --- 2. The rules, ordered, editable, first match wins --------------------------------------------
--
-- ORDERED RATHER THAN SCORED, AND FIRST MATCH WINS. A scoring system would need somebody to explain
-- why a row came out where it did; an ordered list is readable top to bottom by the person who
-- edits it, and "rule 30 caught it" is an answer a merchandiser can act on. `classified_rule_id`
-- on the product records which one, so the workspace can say so per row.

create table research_large_format_rules (
  id              uuid primary key default gen_random_uuid(),

  -- UNIQUE, so two rules can never tie and the order is never ambiguous. Seeded in tens, which is
  -- the convention that leaves room to insert one between two without renumbering the file.
  priority        integer not null unique,

  /*
   * THE PREDICATE IS DATA, AND ITS SHAPE IS A CLOSED VOCABULARY RATHER THAN AN EXPRESSION.
   *
   * A rule engine that evaluated arbitrary expressions from a jsonb column would be a code path a
   * Studio form can write into — which is the shape of an injection, and would also be impossible
   * to typecheck. `lib/scraper/analytics/scale.ts` reads a fixed set of keys
   * (`parseState`, `minLongestAxisMm`, `categoryInLargeFormatSet`) and ignores anything else, so a
   * predicate somebody invents is inert rather than dangerous.
   */
  predicate       jsonb not null,

  result_band     text,
  result_is_large boolean,

  is_enabled      boolean not null default true,
  notes           text,

  status          content_status not null default 'DRAFT',
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  updated_by      uuid references auth.users (id),

  constraint research_large_format_rules_predicate_is_object
    check (jsonb_typeof(predicate) = 'object'),
  constraint research_large_format_rules_band_allowlist
    check (result_band is null
           or result_band in ('DINING', 'CONSOLE', 'COFFEE', 'SEATING', 'SIDE', 'MONUMENTAL',
                              'WALL', 'UNKNOWN')),
  -- A RULE THAT DECIDES NOTHING IS A RULE THAT SHOULD NOT EXIST. It would consume a row's first
  -- match and leave it unclassified, which reads as a classifier bug rather than a configuration one.
  constraint research_large_format_rules_decides_something
    check (result_band is not null or result_is_large is not null)
);

comment on table research_large_format_rules is
  'Ordered scale rules, first match wins, editable in Studio. The predicate is a closed vocabulary of keys read by lib/scraper/analytics/scale.ts rather than an expression: a rule engine evaluating arbitrary jsonb would be a code path a form can write into.';

create index research_large_format_rules_order_idx
  on research_large_format_rules (priority) where is_enabled = true;

-- --- 3. Saved views -------------------------------------------------------------------------------
--
-- "LARGE DINING TABLES, ONE CURRENCY, IN STOCK, LAST THIRTY DAYS" IS A LINK, NOT A SET OF
-- INSTRUCTIONS. A filter set that lives only in somebody's head is one nobody else can reproduce,
-- and the first thing that happens to an analysis nobody can reproduce is that it stops being
-- believed.
--
-- PER SURFACE AND REUSABLE. Phases 31 to 35 each add a surface with filters; storing views here,
-- keyed by surface, is what stops each of them inventing its own saved-view table.

create table research_saved_views (
  id             uuid primary key default gen_random_uuid(),

  surface        text not null,
  name           text not null,
  filters        jsonb not null,
  sort           jsonb,
  columns        text[],

  -- SHARED IS OPT-IN AND READ-ONLY TO EVERYBODY ELSE. A view somebody else can edit is a view whose
  -- results change under the person who linked to it.
  is_shared      boolean not null default false,
  owner_user_id  uuid not null references auth.users (id) on delete cascade,

  status         content_status not null default 'PUBLISHED',
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),
  updated_by     uuid references auth.users (id),

  constraint research_saved_views_surface_allowlist
    check (surface in ('explorer', 'large-format', 'changes', 'compare')),
  constraint research_saved_views_name_not_blank check (btrim(name) <> ''),
  constraint research_saved_views_filters_is_object check (jsonb_typeof(filters) = 'object'),
  constraint research_saved_views_unique_per_owner unique (owner_user_id, surface, name)
);

comment on table research_saved_views is
  'A named filter set per surface, reproducible from its URL and shareable. Keyed by surface so Phases 31-35 reuse it rather than each inventing a saved-view table. A shared view is readable by anyone with research.read and editable only by its owner.';

create index research_saved_views_by_surface_idx
  on research_saved_views (surface, owner_user_id);
create index research_saved_views_shared_idx
  on research_saved_views (surface) where is_shared = true;

-- --- 4. The five default rules --------------------------------------------------------------------
--
-- SEEDED AS CONFIGURATION FOR `0260`'s AND `0270`'s REASON: a classifier with no rules classifies
-- nothing, and a system that cannot run until somebody seeds it is a system that will be found
-- broken by whoever first tries to use it. The numbers are the phase document's table verbatim.
--
-- RULE 10 IS FIRST AND THAT ORDER IS THE WHOLE DESIGN. An unparsed row reaches `UNKNOWN` before any
-- threshold is consulted, so no measurement rule ever sees a row it has no measurements for.

-- check-migrations: allow-insert (the five ordered rules the classifier needs in order to place anything at all, editable in Studio thereafter — configuration, not content)
insert into research_large_format_rules (priority, predicate, result_band, result_is_large, notes, status) values
  (10, '{"parseState": "NOT_PARSED"}'::jsonb, 'UNKNOWN', null,
       'An unmeasured row is not a small row. First, so no threshold ever sees a row with no measurements.',
       'PUBLISHED'),
  (20, '{"minLongestAxisMm": 1800}'::jsonb, null, true,
       'Long enough that nothing else needs asking.', 'PUBLISHED'),
  (30, '{"minLongestAxisMm": 1200, "categoryInLargeFormatSet": true}'::jsonb, null, true,
       'Long, and in a category Rivya has mapped as large-format.', 'PUBLISHED'),
  (40, '{"minLongestAxisMm": 1200}'::jsonb, null, false,
       'Long, but in no category that makes it large-format. MID.', 'PUBLISHED'),
  (50, '{}'::jsonb, null, false,
       'Otherwise. An empty predicate matches everything, which is what a fallthrough is.',
       'PUBLISHED');

-- --- 5. RLS on, policies in 0281 ------------------------------------------------------------------

alter table research_large_format_rules enable row level security;
alter table research_saved_views        enable row level security;
