import type { SupabaseClient } from '@supabase/supabase-js'
import { z } from 'zod'

import type { Database } from '../database.types'
import { PermissionError } from '../errors'
import {
  inquiryAttachmentSchema,
  inquiryEventSchema,
  inquirySchema,
  referenceCodeSchema,
  type Inquiry,
  type InquiryAttachment,
  type InquiryEvent,
} from '../schemas'
import { parseRow, parseRows, toRepositoryError } from './support'

type Client = SupabaseClient<Database>

const ENTITY = 'inquiry'

/**
 * `inquiries` and its two companions — the only module that reads or writes them.
 *
 * THE PUBLIC WRITE PATH USES THE ANONYMOUS CLIENT ON PURPOSE. Every other write in this codebase
 * runs behind `requirePermission`; this one has no session to check, because D1 forbids customer
 * accounts and the person filling in the form is nobody. So the RLS policy is the whole guard, and
 * using the service-role client here would bypass the one thing standing between an HTML form and
 * the table. `createInquiry` takes an ordinary client and expects to be handed the anon one.
 *
 * IT DOES NOT READ BACK, AND CANNOT. PostgreSQL applies a table's SELECT policy to an INSERT's
 * RETURNING clause, and `inquiries` has no anon SELECT policy — so `.select()` on the insert would
 * fail with `new row violates row-level security policy`, which reads exactly like a rejected write
 * and is not one. The id is generated by the CALLER and passed in; the reference code, which a
 * trigger allocates, comes back from `inquiryReferenceCode()`. Amendment A20 records the finding.
 *
 * EVERYTHING ELSE IS STAFF WORK and goes through the request-scoped session client, so RLS refuses
 * underneath the permission check as well as beside it.
 */

/**
 * Write the enquiry. Returns nothing, because there is nothing it is allowed to read.
 *
 * THE CALLER OWNS THE `id`. That is what makes the rest of the flow possible without giving `anon`
 * a select policy: the caller already holds the identifier of the row it just wrote, and every
 * follow-up — the reference code, the attachments, the handoff record — is addressed by it.
 */
export type InquiryInsert = Omit<
  Database['public']['Tables']['inquiries']['Insert'],
  'reference_code'
>

export async function createInquiry(client: Client, values: InquiryInsert): Promise<void> {
  /*
   * `reference_code` IS OMITTED FROM THE PARAMETER AND FROM THE PAYLOAD, and the cast is what says
   * so out loud. The column is `not null` with no default, so the generated types require it; the
   * BEFORE trigger allocates it and OVERWRITES anything supplied, so sending a value would be
   * sending something the database throws away. Widening the column with a default would weaken the
   * shape CHECK to accommodate a placeholder nothing ever reads.
   */
  const { error } = await client
    .from('inquiries')
    .insert(values as Database['public']['Tables']['inquiries']['Insert'])
  if (error) throw toRepositoryError(ENTITY, 'insert', values.id ?? '(new)', error)
}

/** The trigger-allocated code, for an enquiry created in the last ten minutes. */
export async function inquiryReferenceCode(client: Client, inquiryId: string): Promise<string> {
  const { data, error } = await client.rpc('inquiry_reference_code', { p_inquiry_id: inquiryId })
  if (error) throw toRepositoryError(ENTITY, 'reference-code', inquiryId, error)

  const parsed = referenceCodeSchema.safeParse(data)
  // No code came back for a row that was just written: the ten-minute window is the only thing that
  // can do that, and a clock that far out is worth failing on rather than papering over.
  if (!parsed.success) throw new PermissionError('reference-code', ENTITY)
  return parsed.data
}

/**
 * Turn the visitor's uploaded references into asset rows and link them. Returns how many landed.
 *
 * A REFERENCE OUTSIDE THE INCOMING FOLDER IS NOT ATTACHED AND NOT REPORTED. The function refuses it
 * silently, because saying which `public_id` was rejected tells a caller which ones exist.
 */
export async function attachInquiryReferences(
  client: Client,
  inquiryId: string,
  references: readonly { publicId: string; filename: string }[],
): Promise<number> {
  const { data, error } = await client.rpc('attach_inquiry_references', {
    p_inquiry_id: inquiryId,
    p_references:
      references as unknown as Database['public']['Tables']['inquiries']['Row']['answers'],
  })
  if (error) throw toRepositoryError(ENTITY, 'attach-references', inquiryId, error)
  return z.number().int().catch(0).parse(data)
}

/**
 * Record what happened to the handoff. `false` means the row had already moved on.
 *
 * IT NEVER THROWS FOR A ROW THAT WAS NOT UPDATED, because by the time this runs the enquiry is
 * SAVED — which is the outcome that matters — and failing here would turn a bookkeeping miss into a
 * visible error on a submission that succeeded.
 */
export async function recordInquiryHandoff(
  client: Client,
  inquiryId: string,
  state: 'REDIRECTED' | 'SHORTENED' | 'UNAVAILABLE',
  level: number | null,
): Promise<boolean> {
  const { data, error } = await client.rpc('record_inquiry_handoff', {
    p_inquiry_id: inquiryId,
    p_state: state,
    p_level: level,
  })
  if (error) throw toRepositoryError(ENTITY, 'record-handoff', inquiryId, error)
  return data === true
}

// -------------------------------------------------------------------------------------------------
// The Studio side
// -------------------------------------------------------------------------------------------------

export type InquiryFilter = {
  readonly kind?: Database['public']['Enums']['inquiry_kind']
  readonly status?: Database['public']['Enums']['inquiry_status']
  readonly assignedTo?: string
  readonly limit?: number
  readonly offset?: number
}

export async function listInquiriesForStudio(
  client: Client,
  filter: InquiryFilter = {},
): Promise<Inquiry[]> {
  const from = filter.offset ?? 0
  const to = from + (filter.limit ?? 50) - 1

  let query = client.from('inquiries').select('*')
  if (filter.kind !== undefined) query = query.eq('kind', filter.kind)
  if (filter.status !== undefined) query = query.eq('pipeline_status', filter.status)
  if (filter.assignedTo !== undefined) query = query.eq('assigned_to', filter.assignedTo)

  const { data, error } = await query
    .order('created_at', { ascending: false })
    .order('id', { ascending: true })
    .range(from, to)

  if (error) throw toRepositoryError(ENTITY, 'list', 'studio', error)
  return parseRows(ENTITY, inquirySchema, data ?? [])
}

/** One enquiry, or `null` when this role cannot see it — which is indistinguishable from absent. */
export async function getInquiryForStudio(client: Client, id: string): Promise<Inquiry | null> {
  const { data, error } = await client.from('inquiries').select('*').eq('id', id).maybeSingle()
  if (error) throw toRepositoryError(ENTITY, 'get', id, error)
  return data === null ? null : parseRow(ENTITY, inquirySchema, data)
}

export async function listInquiryAttachments(
  client: Client,
  inquiryId: string,
): Promise<InquiryAttachment[]> {
  const { data, error } = await client
    .from('inquiry_attachments')
    .select('*')
    .eq('inquiry_id', inquiryId)
    .order('position', { ascending: true })

  if (error) throw toRepositoryError('inquiry attachment', 'list', inquiryId, error)
  return parseRows('inquiry attachment', inquiryAttachmentSchema, data ?? [])
}

export async function listInquiryEvents(
  client: Client,
  inquiryId: string,
): Promise<InquiryEvent[]> {
  const { data, error } = await client
    .from('inquiry_events')
    .select('*')
    .eq('inquiry_id', inquiryId)
    .order('occurred_at', { ascending: true })

  if (error) throw toRepositoryError('inquiry event', 'list', inquiryId, error)
  return parseRows('inquiry event', inquiryEventSchema, data ?? [])
}

/**
 * Move an enquiry along the pipeline, and READ IT BACK.
 *
 * The read-back is the check, for the reason every write in this repository carries one: RLS
 * FILTERS AN UPDATE, IT DOES NOT REFUSE ONE. A session without `inquiries.write` matches no row,
 * gets no error, and would be told the status changed. The `STATUS_CHANGED` event is written by
 * trigger from the row itself, so a change made through PostgREST is recorded as surely as one made
 * here.
 */
export async function setInquiryStatus(
  client: Client,
  id: string,
  status: Database['public']['Enums']['inquiry_status'],
  actorId: string,
): Promise<Inquiry> {
  const { data, error } = await client
    .from('inquiries')
    .update({ pipeline_status: status, updated_by: actorId })
    .eq('id', id)
    .select()
    .maybeSingle()

  if (error) throw toRepositoryError(ENTITY, 'set-status', id, error)
  if (data === null) throw new PermissionError('set-status', ENTITY)
  return parseRow(ENTITY, inquirySchema, data)
}

/** Assign, or unassign with `null`. The ASSIGNED event is written by the same trigger. */
export async function assignInquiry(
  client: Client,
  id: string,
  assignee: string | null,
  actorId: string,
): Promise<Inquiry> {
  const { data, error } = await client
    .from('inquiries')
    .update({ assigned_to: assignee, updated_by: actorId })
    .eq('id', id)
    .select()
    .maybeSingle()

  if (error) throw toRepositoryError(ENTITY, 'assign', id, error)
  if (data === null) throw new PermissionError('assign', ENTITY)
  return parseRow(ENTITY, inquirySchema, data)
}

/**
 * Append an event by hand: a note, or the record of an export.
 *
 * THE TABLE IS APPEND-ONLY AND STAFF MAY ONLY APPEND. There is no update policy and a trigger
 * refuses one anyway, so a mistaken note is corrected by writing another — which is the behaviour
 * an event log has to have to be worth reading.
 */
export async function appendInquiryEvent(
  client: Client,
  inquiryId: string,
  event: 'NOTE_ADDED' | 'EXPORTED' | 'VIEWED',
  actorId: string,
  note: string | null,
  metadata: Record<string, unknown> = {},
): Promise<InquiryEvent> {
  const { data, error } = await client
    .from('inquiry_events')
    .insert({
      inquiry_id: inquiryId,
      event,
      actor_id: actorId,
      note,
      metadata: metadata as Database['public']['Tables']['inquiry_events']['Insert']['metadata'],
    })
    .select()
    .maybeSingle()

  if (error) throw toRepositoryError('inquiry event', 'insert', inquiryId, error)
  if (data === null) throw new PermissionError('append-event', 'inquiry event')
  return parseRow('inquiry event', inquiryEventSchema, data)
}

/**
 * Every enquiry for the CSV export, oldest first.
 *
 * IT SELECTS COLUMNS BY NAME AND `ip_hash` AND `user_agent` ARE NOT AMONG THEM. A `select('*')` here
 * would put both into a spreadsheet that leaves the building the moment somebody emails it, and the
 * phase document names that as a risk in its own table. The exclusion is at the query rather than
 * in the CSV writer, so a later change to the writer cannot reintroduce them.
 */
export async function listInquiriesForExport(client: Client): Promise<
  readonly {
    reference_code: string
    kind: string
    pipeline_status: string
    name: string
    phone: string
    email: string | null
    city: string | null
    enquiry_type: string | null
    whatsapp_state: string
    source_path: string | null
    created_at: string
  }[]
> {
  const { data, error } = await client
    .from('inquiries')
    .select(
      'reference_code, kind, pipeline_status, name, phone, email, city, enquiry_type, whatsapp_state, source_path, created_at',
    )
    .order('created_at', { ascending: true })

  if (error) throw toRepositoryError(ENTITY, 'export', 'all', error)
  return data ?? []
}
